package com.daltowacja.daltowacja

val advancedColors_en = mapOf(
    intArrayOf(93, 138, 168) to listOf("Ultramaryna", "Mocno desaturowany ciemny niebieski"),
    intArrayOf(240, 248, 255) to listOf("(eng) Alice Blue", "Bardzo blady (przeważnie biały) niebieski"),
    intArrayOf(227, 38, 54) to listOf("Szkarłat Alizarynowy", "Jasnoczerwony"),
    intArrayOf(239, 222, 205) to listOf("Migdałowy", "Lekko szary pomarańczowy"),
    intArrayOf(229, 43, 80) to listOf("Amarantowy", "Jasnoczerwony"),
    intArrayOf(255, 191, 0) to listOf("Bursztynowy", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(255, 3, 62) to listOf("(eng) American Różany", "Jaskrawoczerwony"),
    intArrayOf(153, 102, 204) to listOf("Ametyst", "Umiarkowanie fioletowy"),
    intArrayOf(164, 198, 57) to listOf("Androidowa Zieleń", "Umiarkowanie żółta zieleń"),
    intArrayOf(242, 243, 244) to listOf("Anti-flash White", "Jasnoszaroniebieski"),
    intArrayOf(205, 149, 117) to listOf("Antyczna Miedź", "Lekko desaturowany pomarańczowy"),
    intArrayOf(145, 92, 131) to listOf("Antyczna Fuksja", "Mocno desaturowany ciemny róż"),
    intArrayOf(250, 235, 215) to listOf("Antyczna Biel", "Jasnoszaropomarańczowy"),
    intArrayOf(0, 128, 0) to listOf("Ao", "Ciemny limnonkowo zielony"),
    intArrayOf(141, 182, 0) to listOf("Jabłkowa Zieleń", "Mocno żółty zielony"),
    intArrayOf(251, 206, 177) to listOf("Morelowy", "Bardzo delikatnie pomarańczowyowy"),
    intArrayOf(0, 255, 255) to listOf("Błękit Turkusowy", "Czysty (lub prawie czysty) cyjan"),
    intArrayOf(127, 255, 212) to listOf("Akwamaryna", "Bardzo delikatnie cyjanowa zieleń limonkowa"),
    intArrayOf(75, 83, 32) to listOf("Wojskowa Zieleń", "Mocno ciemnożółty [Oliwkowy odcień]"),
    intArrayOf(233, 214, 107) to listOf("Arylidowy", "Delikatny żółty"),
    intArrayOf(178, 190, 181) to listOf("Popielata Szarość", "Szarawy cyjan - limonkowo zielony"),
    intArrayOf(135, 169, 107) to listOf("Szparagowy", "Mocno desaturowany Ciemnozielony"),
    intArrayOf(255, 153, 102) to listOf("(eng) Atomic Tangerine", "Delikatny pomarańcz"),
    intArrayOf(165, 42, 42) to listOf("(eng) Auburn", "Ciemnoczerwony"),
    intArrayOf(253, 238, 0) to listOf("Żółty Kobaltowy", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(110, 127, 128) to listOf("(eng) AuroMetalSaurus", "ciemnoszary-cyjan"),
    intArrayOf(255, 32, 82) to listOf("(eng) Awesome", "Jaskrawoczerwony"),
    intArrayOf(0, 127, 255) to listOf("Lazurowy", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(240, 255, 255) to listOf("Lazurowa Mgła", "Barszo blady (głównie biały) cyjan"),
    intArrayOf(137, 207, 240) to listOf("Jasnoniebieski", "Delikatny błękit"),
    intArrayOf(244, 194, 194) to listOf("Jasnoróżowy", "Delikatny czerwień"),
    intArrayOf(33, 171, 205) to listOf("(eng) Ball Blue", "Mocny cyjan"),
    intArrayOf(250, 231, 181) to listOf("Bananowa Mania", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(255, 225, 53) to listOf("Bananowy", "Jasnożółty"),
    intArrayOf(132, 132, 130) to listOf("Szary Pancernikowy", "Ciemnoszarożółty"),
    intArrayOf(152, 119, 123) to listOf("Bazaar", "Ciemnoszaroczerwony"),
    intArrayOf(188, 212, 230) to listOf("(eng) Beau Blue", "Jasnoszaroniebieski"),
    intArrayOf(159, 129, 112) to listOf("Bobrowy", "Mocno desaturowany ciemny pomarańcz"),
    intArrayOf(245, 245, 220) to listOf("Beżowy", "Janoszarożółty"),
    intArrayOf(255, 228, 196) to listOf("(eng) Bisque", "Bardzo blady pomarańczowy"),
    intArrayOf(61, 43, 31) to listOf("Hebanowy", "Bardzo ciemny desaturowany pomarańcz"),
    intArrayOf(254, 111, 94) to listOf("Bittersweet", "Delikatny czerwień"),
    intArrayOf(0, 0, 0) to listOf("Czarny", "Czarny"),
    intArrayOf(255, 235, 205) to listOf("Blanszowane Migdały", "Bardzo blady pomarańcz"),
    intArrayOf(49, 140, 231) to listOf("Bleu De France", "Jasnoniebieski"),
    intArrayOf(172, 229, 238) to listOf("Niebieski Śnieżycowy", "Bardzo delikatny cyjan"),
    intArrayOf(250, 240, 190) to listOf("Blond", "Bardzo delikatny żółty"),
    intArrayOf(0, 0, 255) to listOf("Niebieski", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(162, 162, 208) to listOf("Niebieski Dzwon", "Szaro-niebieski"),
    intArrayOf(102, 153, 204) to listOf("Niebiesko-szary", "Umiarkowany niebieski"),
    intArrayOf(13, 152, 186) to listOf("Niebiesko-zielony", "Mocny cyjan"),
    intArrayOf(138, 43, 226) to listOf("Niebiesko-fioletowy", "Jasnofioletowy"),
    intArrayOf(138, 43, 226) to listOf("Niebiesko-fiołkowy", "Jasnofiołkowy"),
    intArrayOf(222, 93, 131) to listOf("Rumieniec", "Delikany róż"),
    intArrayOf(121, 68, 59) to listOf("Pień", "Ciemny umiarkowanie czerwony"),
    intArrayOf(0, 149, 182) to listOf("(eng) Bondi Blue", "Mocny cyjan"),
    intArrayOf(227, 218, 201) to listOf("Kość", "Jasnoszaropomarańczowy"),
    intArrayOf(204, 0, 0) to listOf("Czerwień Uniwersytetu Bostońskiego", "Mocno czerwony"),
    intArrayOf(0, 106, 78) to listOf("Ciemny Oliwkowy", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(135, 50, 96) to listOf("(eng) Boysenberry", "Ciemny umiarkowanie różowy"),
    intArrayOf(0, 112, 255) to listOf("(eng) Brandeis Blue", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(181, 166, 66) to listOf("Miedziany", "Umiarkowanie żółty"),
    intArrayOf(203, 65, 84) to listOf("Ceglana Czerwień", "Umiarkowanie czerwony"),
    intArrayOf(29, 172, 214) to listOf("Jasny Ceruleum", "Mocny cyjan"),
    intArrayOf(102, 255, 0) to listOf("Jasnozielony", "Czysty (lub prawie czysty) zielony"),
    intArrayOf(191, 148, 228) to listOf("Jasny Lawendowy", "Bardzo delikatny fiołkowy"),
    intArrayOf(195, 33, 72) to listOf("Jasny Rdzawy", "Mocna czerwień"),
    intArrayOf(255, 0, 127) to listOf("Jasnoróżowy", "Czysty (lub prawie czysty) różowy"),
    intArrayOf(8, 232, 222) to listOf("Jasny Turkusowy", "Jaskrawy cyjan"),
    intArrayOf(209, 159, 232) to listOf("Jasny Ube", "Bardzo delikatny fiolet"),
    intArrayOf(244, 187, 255) to listOf("Lśniący Lawendowy", "Blada magenta"),
    intArrayOf(255, 85, 163) to listOf("Lśniąca Róża", "Jasnoróżowy"),
    intArrayOf(251, 96, 127) to listOf("Skrajny Róż", "Delikatny czerwień"),
    intArrayOf(0, 66, 37) to listOf("(eng) British Racing Green", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(205, 127, 50) to listOf("Brąz", "Mocno pomarańczowy"),
    intArrayOf(165, 42, 42) to listOf("Brązowy", "Ciemny czerwień"),
    intArrayOf(255, 193, 204) to listOf("Guma Balonowa", "Bardzo blady czerwień"),
    intArrayOf(231, 254, 255) to listOf("Bąbelkowy", "Bardzo blady (głównie biały) cyjan"),
    intArrayOf(240, 220, 130) to listOf("Płowożółty", "Delikatny żółty"),
    intArrayOf(72, 6, 7) to listOf("Bułgarska Róża", "Bardzo ciemny czerwony"),
    intArrayOf(128, 0, 32) to listOf("Burgund", "Ciemny czerwień"),
    intArrayOf(222, 184, 135) to listOf("(eng) Burlywood", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(204, 85, 0) to listOf("Spalona Pomarańcza", "Mocno pomarańczowy"),
    intArrayOf(233, 116, 81) to listOf("Spalona Sjena", "Delikany czerwony"),
    intArrayOf(138, 51, 36) to listOf("Spalona Umbra", "Ciemny czerwień"),
    intArrayOf(189, 51, 164) to listOf("Bizantyjski", "Umiarkowana magenta"),
    intArrayOf(112, 41, 99) to listOf("Bizancjum", "Bardzo ciemna magenta"),
    intArrayOf(0, 122, 165) to listOf("(eng) CG Blue", "Ciemnoniebieski"),
    intArrayOf(224, 60, 49) to listOf("(eng) CG Red", "Jasnoczerwony"),
    intArrayOf(83, 104, 114) to listOf("Kadet", "Bardzo ciemno szaro niebieski"),
    intArrayOf(95, 158, 160) to listOf("Kadecki Niebieski", "Mocno desaturowany ciemny cyjan"),
    intArrayOf(145, 163, 176) to listOf("Kadecki Szary", "Ciemnoszaroniebieski"),
    intArrayOf(0, 107, 60) to listOf("Zieleń Kadmowa", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(237, 135, 45) to listOf("Pomarańcz Kadmowa", "Jasnopomarańczowy"),
    intArrayOf(227, 0, 34) to listOf("Czerwień Kadmowa", "Czysty (lub prawie czysty) czerwień"),
    intArrayOf(255, 246, 0) to listOf("Żółty Kadmowy", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(166, 123, 91) to listOf("(eng) Café Au Lait", "Ciemny umiarkowany pomarańcz"),
    intArrayOf(75, 54, 33) to listOf("(eng) Café Noir", "Bardzo ciemny desaturowany pomarańcz"),
    intArrayOf(163, 193, 173) to listOf("(eng) Cambridge Blue", "Szarawy cyjan - limonkowo zielony"),
    intArrayOf(193, 154, 107) to listOf("Wielbłąd", "Lekko desaturowany pomarańcz"),
    intArrayOf(120, 134, 107) to listOf("Zielony Kamuflażowy", "Ciemnoszarozielony"),
    intArrayOf(255, 255, 153) to listOf("Kanarkowy", "Bardzo jasny żółty"),
    intArrayOf(255, 8, 0) to listOf("Jabłko Kandyzowane", "Czysty (lub prawie czysty) czerwony"),
    intArrayOf(228, 113, 122) to listOf("Różowy Cukierek", "Delikatny czerwień"),
    intArrayOf(0, 191, 255) to listOf("Capri", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(89, 39, 32) to listOf("(eng) Caput Mortuum", "Bardzo ciemny czerwony"),
    intArrayOf(196, 30, 58) to listOf("Cardinal", "Mocno czerwony"),
    intArrayOf(0, 204, 153) to listOf("Karaibski Zielony", "Mocny cyjan"),
    intArrayOf(255, 0, 64) to listOf("Karminowy", "Czysty (lub prawie czysty) różowy"),
    intArrayOf(235, 76, 66) to listOf("Różowy Karminowy", "Jasnoczerwony"),
    intArrayOf(255, 0, 56) to listOf("Czerowny Karminowy", "Czysty (lub prawie czysty) czerwony"),
    intArrayOf(255, 166, 201) to listOf("(eng) Carnation Pink", "Blady różowy"),
    intArrayOf(179, 27, 27) to listOf("Karneol", "Mocno czerwony"),
    intArrayOf(153, 186, 221) to listOf("(eng) Carolina Blue", "Bardzo delikatny niebieski"),
    intArrayOf(237, 145, 33) to listOf("Marchewkowy", "Jaskrawopomarańczowy"),
    intArrayOf(172, 225, 175) to listOf("Seledynowy", "Bardzo delikatny limonkowo zielony"),
    intArrayOf(178, 255, 255) to listOf("(eng) Celeste", "Blady cyjan"),
    intArrayOf(73, 151, 208) to listOf("Niebiański Niebieski", "Umiarkowanie niebieski"),
    intArrayOf(222, 49, 99) to listOf("(eng) Cerise", "Jasnoróżowy"),
    intArrayOf(0, 123, 167) to listOf("Ceruleum", "Ciemnoniebieski"),
    intArrayOf(42, 82, 190) to listOf("Niebieski Ceruleum", "Mocno niebieski"),
    intArrayOf(160, 120, 90) to listOf("(eng) Chamoisee", "Mocno desaturowany ciemny pomarańcz"),
    intArrayOf(250, 214, 165) to listOf("Szampan", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(54, 69, 79) to listOf("Węgiel", "Bardzo ciemny szaroniebieski"),
    intArrayOf(127, 255, 0) to listOf("(eng) Chartreuse", "Czysty (lub prawie czysty) zielony"),
    intArrayOf(222, 49, 99) to listOf("Wisienka", "Jasnoróżowy"),
    intArrayOf(255, 183, 197) to listOf("Kwiat Wiśni", "Blady czerwony"),
    intArrayOf(205, 92, 92) to listOf("Kasztanowy", "Umiarkowanie czerwony"),
    intArrayOf(210, 105, 30) to listOf("Czekolada", "Mocno pomarańczowy"),
    intArrayOf(255, 167, 0) to listOf("Chromowany Żółty", "Czysty (lub prawie czysty) pomarańcz"),
    intArrayOf(152, 129, 123) to listOf("Popielata Szarość", "Ciemny szaroczerwony"),
    intArrayOf(227, 66, 52) to listOf("Cynober", "Jasnoczerwony"),
    intArrayOf(210, 105, 30) to listOf("Cynamonowy", "Ciemny pomarańcz"),
    intArrayOf(228, 208, 10) to listOf("Cytrynowy", "Jaskrawożółty"),
    intArrayOf(251, 204, 231) to listOf("Klasyczna Róża", "Jasny szaroróżowy"),
    intArrayOf(0, 71, 171) to listOf("Kobalt", "Ciemnoniebieski"),
    intArrayOf(210, 105, 30) to listOf("Kakaowy", "Mocno pomarańczowy"),
    intArrayOf(111, 78, 55) to listOf("Kawowy", "Bardzo ciemny desaturowany pomarańcz"),
    intArrayOf(155, 221, 255) to listOf("(eng) Columbia Blue", "Blady niebieski"),
    intArrayOf(184, 115, 51) to listOf("Miedźany", "Umiarkowany pomarańcz"),
    intArrayOf(153, 102, 102) to listOf("Miedziana Róża", "Mocno desaturowany ciemnoczerwony"),
    intArrayOf(255, 56, 0) to listOf("(eng) Coquelicot", "Czysty (lub prawie czysty) czerwony"),
    intArrayOf(255, 127, 80) to listOf("Koralowy", "Jasnopomarańczowy"),
    intArrayOf(248, 131, 121) to listOf("Różowy Koralowy", "Delikatny czerwony"),
    intArrayOf(255, 64, 64) to listOf("Czerwony Koralowy", "Jasnoczerwony"),
    intArrayOf(137, 63, 69) to listOf("Kurdyban", "Ciemny umiarkowanie czerwony"),
    intArrayOf(251, 236, 93) to listOf("Kukurydziany", "Delikatny żółty"),
    intArrayOf(179, 27, 27) to listOf("(eng) Cornell Red", "Mocno czerwony"),
    intArrayOf(154, 206, 235) to listOf("Chabrowy", "Bardzo delikatny niebieski"),
    intArrayOf(100, 149, 237) to listOf("Niebieski Chabrowy", "delikatny niebieski"),
    intArrayOf(255, 248, 220) to listOf("Wąs Kukurydzy", "Bardzo blady żółty"),
    intArrayOf(255, 248, 231) to listOf("(eng) Cosmic Latte", "Bardzo blady (przeważnie biały) pomarańczowy"),
    intArrayOf(255, 188, 217) to listOf("Wata Cukrowa", "Blady różowy"),
    intArrayOf(255, 253, 208) to listOf("Kremowy", "Bardzo blady żółty"),
    intArrayOf(220, 20, 60) to listOf("Karmazynowy", "Jaskrawoczerwony"),
    intArrayOf(153, 0, 0) to listOf("Czerwony Karmazynowy", "Ciemnoczerwony"),
    intArrayOf(190, 0, 50) to listOf("Karmazynowa Chwała", "Mocno różowy"),
    intArrayOf(0, 255, 255) to listOf("Cyjan", "Czysty (lub prawie czysty) cyjan"),
    intArrayOf(255, 255, 49) to listOf("Narcyzowy", "Jaskrawożółty"),
    intArrayOf(240, 225, 48) to listOf("Mniszek Lekarski", "Jasnożółty"),
    intArrayOf(0, 0, 139) to listOf("Ciemnoniebieski", "Ciemnoniebieski"),
    intArrayOf(101, 67, 33) to listOf("Ciemnobrązowy", "Bardzo ciemny pomarańczowy [brązowy odcień]"),
    intArrayOf(93, 57, 84) to listOf("Ciemny Bizancjum", "Bardzo ciemna desaturowana magenta"),
    intArrayOf(164, 0, 0) to listOf("Ciemne Jabłko Kandyzowane", "Ciemnoczerwony"),
    intArrayOf(8, 69, 126) to listOf("Ciemny Modry", "Ciemnoniebieski"),
    intArrayOf(152, 105, 96) to listOf("Ciemny Kasztan", "Mocno desaturowany ciemnoczerwony"),
    intArrayOf(205, 91, 69) to listOf("Ciemny Koralowy", "Umiarkowanie czerwony"),
    intArrayOf(0, 139, 139) to listOf("Ciemnocyjanowy", "Ciemnocyjanowy"),
    intArrayOf(83, 104, 120) to listOf("Ciemny Elektryczny Niebieski", "Mocno desaturowany ciemnoniebieski"),
    intArrayOf(184, 134, 11) to listOf("(eng) Dark Złotyrod", "Mocno pomarańczowy"),
    intArrayOf(169, 169, 169) to listOf("Ciemnoszary", "Szary"),
    intArrayOf(1, 50, 32) to listOf("Ciemnozielony", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(26, 36, 33) to listOf("Zieleń Ciemnej Dżungli", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(189, 183, 107) to listOf("Ciemny Khaki", "Lekko desaturowany żółty"),
    intArrayOf(72, 60, 50) to listOf("Ciemna Lawa", "Bardzo ciemny szarawopomarańczowy Bardzo ciemny szaropomarańczowy"),
    intArrayOf(115, 79, 150) to listOf("Ciemna Lawenda", "Ciemny umiarkowanie fiołkowy"),
    intArrayOf(139, 0, 139) to listOf("Ciemna Magenta", "Ciemna magenta"),
    intArrayOf(0, 51, 102) to listOf("(eng) Ciemny Midnight Blue", "Bardzo ciemny niebieski"),
    intArrayOf(85, 107, 47) to listOf("Ciemny Oliwkowo Zielony", "Bardzo ciemny desaturowany zielony"),
    intArrayOf(255, 140, 0) to listOf("Ciemnopomarańczowy", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(153, 50, 204) to listOf("Ciemna Orchidea", "Mocno fiołkowy"),
    intArrayOf(119, 158, 203) to listOf("Ciemny Pastelowy Niebieski", "Lekko desaturowany niebieski"),
    intArrayOf(3, 192, 60) to listOf("Ciemny Pasteloy Zieleń", "Mocny cyjan - limonkowo zielony"),
    intArrayOf(150, 111, 214) to listOf("Ciemny Pastelowy Fiolet", "Lekko desaturowany fiołkowy"),
    intArrayOf(194, 59, 34) to listOf("Ciemny Pastelowy Czerwień", "Mocno czerwony"),
    intArrayOf(231, 84, 128) to listOf("Ciemny Różowy", "Delikatny róż"),
    intArrayOf(0, 51, 153) to listOf("Ciemny Proszkowy Niebieski", "Ciemny niebieski"),
    intArrayOf(135, 38, 87) to listOf("Ciemna Malina", "Ciemnoróżowy"),
    intArrayOf(139, 0, 0) to listOf("Ciemnoczerwony", "Ciemnoczerwony"),
    intArrayOf(233, 150, 122) to listOf("Ciemny Łososiowy", "Delikatny pomarańcz"),
    intArrayOf(86, 3, 25) to listOf("Ciemny Szkarłat", "Bardzo ciemny róż"),
    intArrayOf(143, 188, 143) to listOf("Zieleń Ciemnego Morza", "Szarawy limonkowo zielony"),
    intArrayOf(60, 20, 20) to listOf("Ciemna Sjena", "Bardzo ciemno czerwony"),
    intArrayOf(72, 61, 139) to listOf("Ciemnoniebieski Łupek", "Ciemny umiarkowanie niebieski"),
    intArrayOf(47, 79, 79) to listOf("Ciemnoszary Łupek", "Bardzo ciemny desaturowany cyjan"),
    intArrayOf(23, 114, 69) to listOf("Wiosenna Ciemna Zieleń", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(145, 129, 81) to listOf("Ciemna Obladynizna", "Mocno desaturowany ciemnożółty"),
    intArrayOf(255, 168, 18) to listOf("Ciemna Mandarynka", "Jaskrawopomarańczowy"),
    intArrayOf(72, 60, 50) to listOf("Ciemny Kreci", "Bardzo ciemny szaropomarańczowy"),
    intArrayOf(204, 78, 92) to listOf("Ciemna Terra Cotta", "Umiarkowanie czerwony"),
    intArrayOf(0, 206, 209) to listOf("Ciemny Turkusowy", "Mocno cyjanowy"),
    intArrayOf(148, 0, 211) to listOf("Ciemny Fiołkowy", "Mocno fiołkowy"),
    intArrayOf(0, 105, 62) to listOf("(eng) Dartmouth Green", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(85, 85, 85) to listOf("(eng) Davy Grey", "Bardzo ciemny szary"),
    intArrayOf(215, 10, 83) to listOf("(eng) Debian Red", "Mocno różowy"),
    intArrayOf(169, 32, 62) to listOf("Głęboki Karminowy", "Ciemnoczerwony"),
    intArrayOf(239, 48, 56) to listOf("Głęboki Karminowy Róż", "Jasnoczerwony"),
    intArrayOf(233, 105, 44) to listOf("Głęboka Pomarańcz Marchewkowa", "Jasnopomarańczowy"),
    intArrayOf(218, 50, 135) to listOf("Głęboki Jasnoczerwony", "Jasnoróżowy"),
    intArrayOf(250, 214, 165) to listOf("Głęboki Szampanowy", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(185, 78, 72) to listOf("Głęboki Kasztan", "Umiarkowanie czerwony"),
    intArrayOf(112, 66, 65) to listOf("Głęboki Kawowy", "Bardzo ciemny desaturowany czerwień"),
    intArrayOf(193, 84, 193) to listOf("Głęboka Fuksja", "Umiarkowana magenta"),
    intArrayOf(0, 75, 73) to listOf("Głęboka Zieleń Dżungli", "Bardzo ciemny cyjan"),
    intArrayOf(153, 85, 187) to listOf("Głęboki Liliowy", "Umiarkowanie fiołkowy"),
    intArrayOf(204, 0, 204) to listOf("Głęboka Magenta", "Mocna magenta"),
    intArrayOf(255, 203, 164) to listOf("Głęboki Brzoskwiniowy", "Blady pomarańcz"),
    intArrayOf(255, 20, 147) to listOf("Głęboki Różowy", "Jaskraworóżowy"),
    intArrayOf(255, 153, 51) to listOf("Głęboki Szafran", "Jaskrawopomarańczowy"),
    intArrayOf(0, 191, 255) to listOf("Głęboki Błękit Nieba", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(21, 96, 189) to listOf("Drelichowy", "Mocno niebieski"),
    intArrayOf(193, 154, 107) to listOf("Pustynny", "Delikatnie desaturowana pomarańcz"),
    intArrayOf(237, 201, 175) to listOf("Pustynny Piasek", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(105, 105, 105) to listOf("Przyćmiony Szary", "Bardzo ciemny szary"),
    intArrayOf(30, 144, 255) to listOf("(eng) Dodger Blue", "Jaskrawoniebieski"),
    intArrayOf(215, 24, 104) to listOf("Róża Dereniowa", "Mocno różowy"),
    intArrayOf(133, 187, 101) to listOf("Dolar", "Delikatnie desaturowany zielony"),
    intArrayOf(150, 113, 23) to listOf("Bury", "Ciemny pomarańcz [Brązowy odcień]"),
    intArrayOf(0, 0, 156) to listOf("Książęcy Niebieski", "Ciemnoniebieski"),
    intArrayOf(225, 169, 95) to listOf("Ziemisty Żółty", "Delikatny pomarańcz"),
    intArrayOf(194, 178, 128) to listOf("Ecru", "Delikatnie desaturowany żółty"),
    intArrayOf(97, 64, 81) to listOf("Bakłażan", "Bardzo ciemny szaroróżowy"),
    intArrayOf(240, 234, 214) to listOf("Skorupkowy", "Jasnoszarożółty"),
    intArrayOf(16, 52, 166) to listOf("Egipski Niebieski", "Ciemnoniebieski"),
    intArrayOf(125, 249, 255) to listOf("Jaskrawoniebieski", "Bardzo jasny cyjan"),
    intArrayOf(255, 0, 63) to listOf("Jaskrawokarmazynowy", "Czysty (lub prawie czysty) czerwień"),
    intArrayOf(0, 255, 255) to listOf("Jaskrawocyjanowy", "Czysty (lub prawie czysty) cyjan"),
    intArrayOf(0, 255, 0) to listOf("Jaskrawozielony", "Czysty (lub prawie czysty) limonkowo zielony"),
    intArrayOf(111, 0, 255) to listOf("Jaskrawy Indygo", "Czysty (lub prawie czysty) fiołkowy"),
    intArrayOf(244, 187, 255) to listOf("Jaskrawolawendowy", "Blada magenta"),
    intArrayOf(204, 255, 0) to listOf("Jaskrawolimonkowy", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(191, 0, 255) to listOf("Jaskrawofioletowy", "Czysty (lub prawie czysty) fiołkowy"),
    intArrayOf(63, 0, 255) to listOf("Jaskrawa Ultramaryna", "Czysty (lub prawie czysty) niebieski"),
    intArrayOf(143, 0, 255) to listOf("Jaskrawofiołkowy", "Czysty (lub prawie czysty) fiołkowy"),
    intArrayOf(255, 255, 0) to listOf("Jaskrawożółty", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(80, 200, 120) to listOf("Szmaragdowy", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(150, 200, 162) to listOf("(eng) Eton Blue", "Szaro-limonkowo zielony"),
    intArrayOf(193, 154, 107) to listOf("Płowy", "Delikatnie desaturowany pomarańcz"),
    intArrayOf(128, 24, 24) to listOf("Czerwień Faluńska", "Ciemnoczerwony"),
    intArrayOf(255, 0, 255) to listOf("(eng) Famous", "Czysta (lub prawie czysta) magenta"),
    intArrayOf(181, 51, 137) to listOf("Fandango", "Umiarkowanie różowy"),
    intArrayOf(244, 0, 161) to listOf("Modna Fuksja", "Czysty (lub prawie czysty) róż"),
    intArrayOf(229, 170, 112) to listOf("Sarna", "Delikatny pomarańcz"),
    intArrayOf(77, 93, 83) to listOf("Polowa Szarość", "Bardzo ciemny szary cyjan - limonkowo zielony"),
    intArrayOf(113, 188, 120) to listOf("Paproć", "Delikatnie desaturowany limonkowo zielony"),
    intArrayOf(79, 121, 66) to listOf("Zieleń Paproci", "Ciemny, umiarkowanie limonkowo zielony"),
    intArrayOf(255, 40, 0) to listOf("Czerwień Ferrari", "Czysty (lub prawie czysty) czerwony"),
    intArrayOf(108, 84, 30) to listOf("Bure Pole", "Bardzo ciemny pomarańcz [Brązowy odcień]"),
    intArrayOf(206, 32, 41) to listOf("(eng) Fire Engine Red", "Mocno czerwony"),
    intArrayOf(178, 34, 34) to listOf("Minia", "Ciemnoczerwony"),
    intArrayOf(226, 88, 34) to listOf("Płomień", "Jasnopomarańczowy"),
    intArrayOf(252, 142, 172) to listOf("Róż Flaminga", "Bardzo delikatny róż"),
    intArrayOf(247, 233, 142) to listOf("Żółtawy", "Bardzo delikatny żółty"),
    intArrayOf(238, 220, 130) to listOf("Len Zwyczajny", "Delikatny żółty"),
    intArrayOf(255, 250, 240) to listOf("Kwiecista Biel", "Bardzo blady (głównie biały) pomarańcz"),
    intArrayOf(255, 191, 0) to listOf("Fluorescencyjny Pomarańczowy", "Czysty (lub prawie czysty) pomarańcz"),
    intArrayOf(255, 20, 147) to listOf("Fluorescencyjny Różowy", "Jaskraworóżowy"),
    intArrayOf(204, 255, 0) to listOf("Fluorescencyjny Żółty", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(255, 0, 79) to listOf("(eng) Folly", "Czysty (lub prawie czysty) róż"),
    intArrayOf(34, 139, 34) to listOf("Leśna Zieleń", "Ciemno limonkowo zielony"),
    intArrayOf(166, 123, 91) to listOf("Francuski Beż", "Ciemny, umiarkowanie pomarańczowy"),
    intArrayOf(0, 114, 187) to listOf("Francuski Błękit", "Mocno niebieski"),
    intArrayOf(134, 96, 142) to listOf("Francuski Liliowy", "Mocno desaturowana ciemna magenta"),
    intArrayOf(246, 74, 138) to listOf("Francuska Róża", "Delikatny róż"),
    intArrayOf(255, 0, 255) to listOf("Fuksja", "Czysta (lub prawie czysta) magenta"),
    intArrayOf(255, 119, 255) to listOf("Różowa Fuksja", "Bardzo jasna magenta"),
    intArrayOf(228, 132, 0) to listOf("Żółtobrązowy", "Czysty (lub prawie czysty) pomarańcz"),
    intArrayOf(204, 102, 102) to listOf("(eng) Fuzzy Wuzzy", "Umiarkowanie czerwony"),
    intArrayOf(220, 220, 220) to listOf("Gainsboro", "Bardzo jasny szary"),
    intArrayOf(228, 155, 15) to listOf("Gumiguta", "Jaskrawopomarańczowy"),
    intArrayOf(248, 248, 255) to listOf("Ghost White", "Bardzo blady (głównie biały) niebieski"),
    intArrayOf(176, 101, 0) to listOf("Rudy", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(96, 130, 182) to listOf("Zielonkawoniebieski", "Delikatnie desaturowany niebieski"),
    intArrayOf(230, 232, 250) to listOf("Brokat", "Jasny szaronibieski"),
    intArrayOf(255, 215, 0) to listOf("Żółto-miodowy", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(153, 101, 21) to listOf("Złoty Brązowy", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(252, 194, 0) to listOf("Złoty Mak", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(255, 223, 0) to listOf("Złoty Żółty", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(218, 165, 32) to listOf("Kwiat Nawłoci", "Jaskrawopomarańczowy"),
    intArrayOf(168, 228, 160) to listOf("Jabłko Granny Smith", "Bardzo delikatny limonkowo-zielony"),
    intArrayOf(128, 128, 128) to listOf("Szary", "Ciemnoszary"),
    intArrayOf(70, 89, 69) to listOf("Szary Szparagowy", "Bardzo ciemny szarolimonkowy"),
    intArrayOf(0, 255, 0) to listOf("Zielony", "Czysty (lub prawie czysty) limonkowo zielony"),
    intArrayOf(17, 100, 180) to listOf("Zielononiebieski", "Mocno niebieski"),
    intArrayOf(173, 255, 47) to listOf("Zielonożółty", "Jaskrawozielony"),
    intArrayOf(169, 154, 134) to listOf("Grullo", "Ciemny szaropomarańczowy"),
    intArrayOf(0, 255, 127) to listOf("Zieleń Gupikowa", "Czysty (lub prawie czysty) cyjan - limonkowo zielony"),
    intArrayOf(102, 56, 84) to listOf("Halayà Úbe", "Bardzo ciemny desaturowany róż"),
    intArrayOf(68, 108, 207) to listOf("(eng) Han Blue", "Umiarkowany niebieski"),
    intArrayOf(82, 24, 250) to listOf("(eng) Han Purple", "Jaskrawofiołkowy"),
    intArrayOf(233, 214, 107) to listOf("Arilydowy", "Delikatny żółty"),
    intArrayOf(63, 255, 0) to listOf("Harlequin", "Czysty (lub prawie czysty) limonkowo zielony"),
    intArrayOf(201, 0, 22) to listOf("Karmazyn Harwardzki", "Mocno czerwony"),
    intArrayOf(218, 145, 0) to listOf("Złociste Plony", "Czysty (lub prawie czysty) pomarańcz"),
    intArrayOf(128, 128, 0) to listOf("(eng) Heart Gold", "Ciemnożółty [Oliwkowy odcień]"),
    intArrayOf(223, 115, 255) to listOf("Heliotrop Peruwiański", "Bardzo jasna magenta"),
    intArrayOf(244, 0, 161) to listOf("(eng) Hollywood Cerise", "Czysty (lub prawie czysty) róż"),
    intArrayOf(240, 255, 240) to listOf("Spadziowy", "Bardzo blady (głównie biały) limonkowo zielony"),
    intArrayOf(73, 121, 107) to listOf("Zieleń Hookera", "Mocno desaturowany ciemny cyjan - limonkowo zielony"),
    intArrayOf(255, 29, 206) to listOf("Płomienna Magenta", "Jaskrawa magenta"),
    intArrayOf(255, 105, 180) to listOf("Płomienny Różowy", "Bardzo jasny różowy"),
    intArrayOf(53, 94, 59) to listOf("Myśliwska Zieleń", "Bardzo ciemna desaturowana limonkowa zieleń"),
    intArrayOf(252, 247, 94) to listOf("(eng) Icterine", "Delikatny żółty"),
    intArrayOf(178, 236, 93) to listOf("(eng) Inchworm", "Delikatna zieleń"),
    intArrayOf(19, 136, 8) to listOf("Zieleń Indyjska", "Ciemno limonkowo zielony"),
    intArrayOf(205, 92, 92) to listOf("Czerwień Indyjska", "Umiarkowanie czerwony"),
    intArrayOf(227, 168, 87) to listOf("Indyjski Żółty", "Delikatny pomarańcz"),
    intArrayOf(75, 0, 130) to listOf("Indygo", "Ciemny fiołkowy"),
    intArrayOf(0, 47, 167) to listOf("Międzynarodowy Klein Blue", "Ciemnoniebieski"),
    intArrayOf(255, 79, 0) to listOf("Międzynarodowy Pomarańcz", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(90, 79, 207) to listOf("Irys", "Umiarkowanie niebieski"),
    intArrayOf(244, 240, 236) to listOf("Izabelin", "Jasnoszaropomarańczowy"),
    intArrayOf(0, 144, 0) to listOf("Zieleń Islamu", "Ciemna limonkowa zieleń"),
    intArrayOf(255, 255, 240) to listOf("Kość Słoniowa", "Bardzo blady (głównie biały) żółty"),
    intArrayOf(0, 168, 107) to listOf("Jadeitowy", "Ciemny cyjan - limonkowo zielony"),
    intArrayOf(248, 222, 126) to listOf("Jaśminowy", "Delikatny żółty"),
    intArrayOf(215, 59, 62) to listOf("Jaspis", "Umiarkowanie czerwony"),
    intArrayOf(165, 11, 94) to listOf("Hibiskus Bylinowy", "Ciemnoróżowy"),
    intArrayOf(250, 218, 94) to listOf("Żonkil", "Delikatny żółty"),
    intArrayOf(189, 218, 87) to listOf("(eng) June Bud", "Delikatny żółty"),
    intArrayOf(41, 171, 135) to listOf("Zieleń Dżungli", "Ciemny cyjan - limonkowo zielony"),
    intArrayOf(232, 0, 13) to listOf("(eng) KU Crimson", "Czysty (lub prawie czysty) czerwony"),
    intArrayOf(76, 187, 23) to listOf("(eng) Kelly Green", "Mocny zieleń"),
    intArrayOf(195, 176, 145) to listOf("Khaki", "Delikatnie desaturowany pomarańcz"),
    intArrayOf(8, 120, 48) to listOf("(eng) La Salle Green", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(214, 202, 221) to listOf("Ospały Lawendowy", "Jasnoszarofiołkowy"),
    intArrayOf(38, 97, 156) to listOf("Lapis Lazuli", "Ciemnoniebieski"),
    intArrayOf(254, 254, 34) to listOf("(eng) Laser Lemon", "Jaskrawożółty"),
    intArrayOf(169, 186, 157) to listOf("Laurowy", "Szaro-zielony"),
    intArrayOf(207, 16, 32) to listOf("Lawa", "Mocno czerwony"),
    intArrayOf(230, 230, 250) to listOf("Lawendowy", "Jasny szaroniebieski"),
    intArrayOf(204, 204, 255) to listOf("Lawendowy Niebieski", "Bardzo blady niebieski"),
    intArrayOf(255, 240, 245) to listOf("Lawendowy Rumieniec", "Bardzo blady (głównie biały) różowy"),
    intArrayOf(196, 195, 208) to listOf("Lawendowy Szary", "Szarawo-niebieski"),
    intArrayOf(148, 87, 235) to listOf("Lawendowe Indygo", "Delikatny fiołkowy"),
    intArrayOf(238, 130, 238) to listOf("Lawendowa Magenta", "Delikatna magenta"),
    intArrayOf(230, 230, 250) to listOf("Lawendowa Mgła", "Jasny szaroniebieski"),
    intArrayOf(251, 174, 210) to listOf("Lawendowy Róż", "Bardzo delikatny róż"),
    intArrayOf(150, 123, 182) to listOf("Lawendowy Fiolet", "Delikatnie desaturowany fiołkowy"),
    intArrayOf(251, 160, 227) to listOf("Lawendowa Róża", "Bardzo delikatny róż"),
    intArrayOf(124, 252, 0) to listOf("Zieleń Trawnikowa", "Czysty (lub prawie czysty) zielony"),
    intArrayOf(255, 247, 0) to listOf("Cytrynowy", "Czysty (lub prawie czysty) żółty"),
    intArrayOf(255, 244, 79) to listOf("Żółty Cytrynowy", "Jasnożółty"),
    intArrayOf(255, 250, 205) to listOf("Cytrynowy Szyfon", "Bardzo blady żółty"),
    intArrayOf(191, 255, 0) to listOf("Cytryna I Limonka", "Czysty (lub prawie czysty) zieleń"),
    intArrayOf(245, 105, 145) to listOf("Jasny Karmazyn", "Delikatny róż"),
    intArrayOf(230, 143, 172) to listOf("(eng) Light Thulian Pink", "Bardzo delikatny róż"),
    intArrayOf(253, 213, 177) to listOf("Jasnomorelowy", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(173, 216, 230) to listOf("Jasnoniebieski", "Bardzo delikatny cyjan"),
    intArrayOf(181, 101, 29) to listOf("Jasnobrązowy", "Mocny pomarańczowy"),
    intArrayOf(230, 103, 113) to listOf("Jasny Karminowy Róż", "Delikatny czerwień"),
    intArrayOf(240, 128, 128) to listOf("Jasny Koralowy", "Delikatny czerwień"),
    intArrayOf(147, 204, 234) to listOf("Jasny Chabrowy", "Bardzo delikatny niebieski"),
    intArrayOf(224, 255, 255) to listOf("Jasny Cyjan", "Bardzo blady cyjan"),
    intArrayOf(249, 132, 239) to listOf("Jasna Róż Fuksji", "Delikatna magenta"),
    intArrayOf(250, 250, 210) to listOf("Jasny Kwiat Nawłoci", "Jasny szarożółty"),
    intArrayOf(211, 211, 211) to listOf("Jasnoszary", "Jasnoszary"),
    intArrayOf(144, 238, 144) to listOf("Jasnozielony", "Bardo delikatna limonkowa zieleń"),
    intArrayOf(240, 230, 140) to listOf("Jasny Khaki", "Bardzo delikatny żółty"),
    intArrayOf(177, 156, 217) to listOf("Jasny Fiolet Pastelowy", "Bardzo delikatny fiołkowy"),
    intArrayOf(255, 182, 193) to listOf("Jasnoróżowy", "Blady czerwony"),
    intArrayOf(255, 160, 122) to listOf("Jasny Łososiowy", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(255, 153, 153) to listOf("Jasny Łososiowy Różowy", "Bardzo jasny czerwony"),
    intArrayOf(32, 178, 170) to listOf("Jasna Zieleń Morza", "Ciemny cyjan"),
    intArrayOf(135, 206, 250) to listOf("Jasny Błękit Nieba", "Delikatny niebieski"),
    intArrayOf(119, 136, 153) to listOf("Jasnoszary Łupek", "Ciemny szaroniebieski"),
    intArrayOf(179, 139, 109) to listOf("Jasny Kreci", "Lekko desaturowana pomarańcz"),
    intArrayOf(255, 255, 237) to listOf("Jasnożółty", "Bardzo blady (głównie biały) żółty"),
    intArrayOf(200, 162, 200) to listOf("Liliowy", "Szarawa magenta"),
    intArrayOf(191, 255, 0) to listOf("Limonkowy", "Czysty (lub prawie czysty) zielony"),
    intArrayOf(50, 205, 50) to listOf("Limonkowa Zieleń", "Mocna limonkowa zieleń"),
    intArrayOf(25, 89, 5) to listOf("Zieleń Lincolna", "Bardzo ciemny limonkowo zielony"),
    intArrayOf(250, 240, 230) to listOf("Len", "Jasny szaropomarańczowy"),
    intArrayOf(193, 154, 107) to listOf("Lew", "Delikatnie desaturowana pomarańcz"),
    intArrayOf(83, 75, 79) to listOf("Wątroba", "Bardzo ciemny szaroróżowy"),
    intArrayOf(230, 32, 32) to listOf("Czerwony Połysk", "Jaskrawoczerowny"),
    intArrayOf(24, 69, 59) to listOf("(eng) MSU Green", "Bardzo ciemny cyjan"),
    intArrayOf(255, 189, 136) to listOf("MAC & Cheese", "Bardzo jasny pomarańcz"),
    intArrayOf(255, 0, 255) to listOf("Magenta", "Czysta (lub prawie czysta) magenta"),
    intArrayOf(170, 240, 209) to listOf("Jasna Mięta", "Bardzo delikatny cyjan - limonkowo zielony"),
    intArrayOf(248, 244, 255) to listOf("Magnolia", "Bardzo blady (głównie biały) fiołkowy"),
    intArrayOf(192, 64, 0) to listOf("Mahoniowy", "Moncno pomarańczowy"),
    intArrayOf(251, 236, 93) to listOf("Kukurydza", "Delikatny żółty"),
    intArrayOf(96, 80, 220) to listOf("(eng) Majorelle Blue", "Delikatny niebieski"),
    intArrayOf(11, 218, 81) to listOf("Malachitowy", "Jaskrawy cyjan - limonkowo zielony"),
    intArrayOf(151, 154, 170) to listOf("Manat", "Ciemny szaroniebieski"),
    intArrayOf(255, 130, 67) to listOf("Mango Tango", "Jasnopomarańczowy"),
    intArrayOf(116, 195, 101) to listOf("Modliszkowy", "Lekko desaturowany limonkowo zielony"),
    intArrayOf(128, 0, 0) to listOf("Rdzawy", "Ciemny czerwień"),
    intArrayOf(224, 176, 255) to listOf("Fioletoworóżowy", "Blady fiołkowy"),
    intArrayOf(145, 95, 109) to listOf("Fioletoworóżowy Kret", "Mocno desaturowany ciemny róż"),
    intArrayOf(239, 152, 170) to listOf("(eng) Fioletoworóżowylous", "Bardzo delikatnie czerwony"),
    intArrayOf(115, 194, 251) to listOf("Błękit Majów", "Delikatny niebieski"),
    intArrayOf(229, 183, 59) to listOf("Mięsny Brązowy", "Jasny pomarańczowy"),
    intArrayOf(0, 103, 165) to listOf("Umiarkowany Perski Błękit", "Ciemnoniebieski"),
    intArrayOf(102, 221, 170) to listOf("Umiarkowana Akwamaryna", "Delikatny cyjan - limonkowo zielony"),
    intArrayOf(0, 0, 205) to listOf("Umiarkowanie Niebieski", "Niebieski"),
    intArrayOf(226, 6, 44) to listOf("Umiarkowana Czrwień Jabłka Kandyzowanego", "Jaskrawoczerowny"),
    intArrayOf(175, 64, 53) to listOf("Umiarkowanie Karminowy", "Ciemny umiarkowanie czerwony"),
    intArrayOf(243, 229, 171) to listOf("Umiarkowana Pomarańcz Szampana", "Bardzo delikatny żółty"),
    intArrayOf(3, 80, 150) to listOf("Umiarkowanie Jaskrawoniebieski", "Ciemnoniebieski"),
    intArrayOf(28, 53, 45) to listOf("Umiarkowana Zieleń Dżungli", "Bardzo ciemny desaturowany cyjan - limonkowo zielony"),
    intArrayOf(221, 160, 221) to listOf("Umiarkowanie Lawendowa Magenta", "Bardzo delikatna magenta"),
    intArrayOf(186, 85, 211) to listOf("(eng) Medium Orchid", "Umiarkowana magenta"),
    intArrayOf(147, 112, 219) to listOf("Umiarkowanie Fioletowy", "Delikatnie fiołkowy"),
    intArrayOf(187, 51, 133) to listOf("Umiarkowana Czerwień Fiołkowa", "Umiarkowanie różowy"),
    intArrayOf(60, 179, 113) to listOf("Umiarkowana Zieleń Morska", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(123, 104, 238) to listOf("Umiarkowanie Niebieski Łupek", "Delikatny niebieski"),
    intArrayOf(201, 220, 135) to listOf("(eng) Medium Spring Bud", "Bardzo delikatnie żółty"),
    intArrayOf(0, 250, 154) to listOf("Umiarkowana Zieleń Wiosenna", "Czysty (lub prawie czysty) cyjan - limonkowo zielony"),
    intArrayOf(103, 76, 71) to listOf("Umiarkowanie Kreci", "Bardzo ciemny szaroczerwony"),
    intArrayOf(0, 84, 180) to listOf("Umiarkowany Błękit Morza", "Mocno niebieski"),
    intArrayOf(72, 209, 204) to listOf("Umiarkowanie Turkusowy", "Umiarkowany cyjan"),
    intArrayOf(199, 21, 133) to listOf("Umiarkowanie Fiołkowa Czerwień", "Mocno różowy"),
    intArrayOf(253, 188, 180) to listOf("Melon", "Bardzo delikatnie czerwony"),
    intArrayOf(25, 25, 112) to listOf("Błękit Północy", "Bardzo ciemny niebieski"),
    intArrayOf(0, 73, 83) to listOf("Zieleń Północy", "Bardzo ciemny cyjan"),
    intArrayOf(255, 196, 12) to listOf("(eng) Mikado Yellow", "Jaskrawożółty"),
    intArrayOf(62, 180, 137) to listOf("Mięta", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(245, 255, 250) to listOf("Krem Miętowy", "Bardzo blady (głównie biały) cyjan - limonkowo zielony"),
    intArrayOf(152, 255, 152) to listOf("Miętowa Zieleń", "Bardzo jasna limonkowa zieleń"),
    intArrayOf(255, 228, 225) to listOf("Mgława Róża", "Bardzo blady czerwień [Różowy odcień]"),
    intArrayOf(250, 235, 215) to listOf("Mokasyny", "Jasny szaropomarańczowy"),
    intArrayOf(150, 113, 23) to listOf("(eng) Mode Beige", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(115, 169, 194) to listOf("Błękit Kamienia Księżycowego", "Delikatnie desaturowany niebieski"),
    intArrayOf(174, 12, 0) to listOf("(eng) Mordant Red 19", "Ciemnoczerwony"),
    intArrayOf(173, 223, 173) to listOf("Zieleń Mchu", "Bardzo delikatny limonkowo zielony"),
    intArrayOf(48, 186, 143) to listOf("Górska Łąka", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(153, 122, 141) to listOf("(eng) Mountbatten Pink", "Ciemny szarawo-różowy"),
    intArrayOf(197, 75, 140) to listOf("Morwowy", "Umiarkowany róż"),
    intArrayOf(242, 243, 244) to listOf("(eng) Munsell", "Jasny szaroniebieski"),
    intArrayOf(255, 219, 88) to listOf("Musztarda", "Jasno żółty"),
    intArrayOf(33, 66, 30) to listOf("Mirtowy", "Bardzo ciemny desaturowany limonkowo zielony"),
    intArrayOf(246, 173, 198) to listOf("(eng) Nadeshiko Pink", "Bardzo delikatny różowy"),
    intArrayOf(42, 128, 0) to listOf("(eng) Napier Green", "Ciemnozielony"),
    intArrayOf(250, 218, 94) to listOf("Żółty Neapolitański", "Delikatnie żółty"),
    intArrayOf(255, 222, 173) to listOf("(eng) Navajo White", "Blady pomarańcz"),
    intArrayOf(0, 0, 128) to listOf("Granatowy", "Ciemnoniebieski"),
    intArrayOf(255, 163, 67) to listOf("Neonowa Marchewka", "Jasnopomarańczowy"),
    intArrayOf(254, 89, 194) to listOf("Neonowa Fuksja", "Delikatnie różowy"),
    intArrayOf(57, 255, 20) to listOf("Neonowa Zieleń", "Jaskrawy limonkowo zielony"),
    intArrayOf(164, 221, 237) to listOf("(eng) Non-photo Blue", "Bardzo delikatny cyjan"),
    intArrayOf(5, 144, 51) to listOf("NZieleń Północnego Teksasu", "Ciemny cyjan - limonkowo zielony"),
    intArrayOf(0, 119, 190) to listOf("(eng) Ocean Boat Blue", "Mocno niebieski"),
    intArrayOf(204, 119, 34) to listOf("Orcha", "Mocno pomarańczowy"),
    intArrayOf(0, 128, 0) to listOf("Biurowa Zieleń", "Ciemny limonkowo zielony"),
    intArrayOf(207, 181, 59) to listOf("Stare Złoto", "Umiarkowany żółty"),
    intArrayOf(253, 245, 230) to listOf("Stara Sznurówka", "Jasny szarawo-pomarańczowy"),
    intArrayOf(121, 104, 120) to listOf("Stara Lawenda", "Ciemna szarawa magenta"),
    intArrayOf(103, 49, 71) to listOf("Stary Fioletoworóżowy", "Bardzo ciemny desaturowany różowy"),
    intArrayOf(192, 128, 129) to listOf("Stara Róża", "Delikatnie desaturowany czerwień"),
    intArrayOf(128, 128, 0) to listOf("Oliwkowy", "Ciemnożółty [Oliwkowy odcień]"),
    intArrayOf(107, 142, 35) to listOf("Oliwkowo-Bury", "Ciemnozielony"),
    intArrayOf(186, 184, 108) to listOf("Oliwkowa Zieleń", "Delikatnie desaturowany żółty"),
    intArrayOf(154, 185, 115) to listOf("Oliwin", "Delikatnie desaturowany zielony"),
    intArrayOf(15, 15, 15) to listOf("Onyks", "Bardzo ciemny szary (głównie czarny)"),
    intArrayOf(183, 132, 167) to listOf("Fioletoworóżowy Opery", "Delikatnie desaturowany różowy"),
    intArrayOf(255, 165, 0) to listOf("Pomarańczowy", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(248, 213, 104) to listOf("Pomarańczowo-żółty", "Delikatnie żółty"),
    intArrayOf(255, 159, 0) to listOf("Skórka Pomarańczy", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(255, 69, 0) to listOf("Pomarańczowo-czerwony", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(218, 112, 214) to listOf("Orchidea", "Delikatna magenta"),
    intArrayOf(101, 67, 33) to listOf("Brązowy Wydry", "Bardzo ciemny pomarańczowy [Brązowy odcień]"),
    intArrayOf(65, 74, 76) to listOf("Przestrzeń Kosmiczna", "Bardzo ciemny szarawy-cyjan"),
    intArrayOf(255, 110, 74) to listOf("(eng) Outrageous Orange", "Jasnoczerwony"),
    intArrayOf(0, 33, 71) to listOf("Niebieski Oxfordzki", "Bardzo Ciemnoniebieski"),
    intArrayOf(28, 169, 201) to listOf("Błękit Pacyfiku", "Mocny cyjan"),
    intArrayOf(0, 102, 0) to listOf("Zieleń Pakistanu", "Bardzo ciemny limonkowo zielony"),
    intArrayOf(39, 59, 226) to listOf("Błękit Palatynatu", "Jasnoniebieski"),
    intArrayOf(104, 40, 96) to listOf("Fiolet Palatynatu", "Bardzo ciemna magenta"),
    intArrayOf(188, 212, 230) to listOf("Blady Błękit Turkusowy", "Jasny szarawo-niebieski"),
    intArrayOf(175, 238, 238) to listOf("Blady Niebieski", "Bardzo delikatny cyjan"),
    intArrayOf(152, 118, 84) to listOf("Blady Brązowy", "Mocno desaturowana ciemna pomarańcza"),
    intArrayOf(175, 64, 53) to listOf("Blady Karminowy", "Ciemny umiarkowanie czerwony"),
    intArrayOf(155, 196, 226) to listOf("Blady Ceruleum", "Bardzo delikatny niebieski"),
    intArrayOf(221, 173, 175) to listOf("Blady Kasztanowy", "Bardzo delikatnie czerwony"),
    intArrayOf(218, 138, 103) to listOf("Blady Miedziany", "Delikatny pomarańcz"),
    intArrayOf(171, 205, 239) to listOf("Blady Chabrowy Błękit", "Bardzo delikatny niebieski"),
    intArrayOf(230, 190, 138) to listOf("Blade Złoto", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(238, 232, 170) to listOf("Blady Kwiat Nawłoci", "Bardzo delikatnie żółty"),
    intArrayOf(152, 251, 152) to listOf("Blady Zielony", "Bardzo delikatny limonkowo zielony"),
    intArrayOf(220, 208, 255) to listOf("Blady Lawendowy", "Bardzo blady fiołkowy"),
    intArrayOf(249, 132, 229) to listOf("Blada Magenta", "Delikatna magenta"),
    intArrayOf(250, 218, 221) to listOf("Blady Różowy", "Jasny szarawo-czerwony"),
    intArrayOf(221, 160, 221) to listOf("Blada Śliwka", "Bardzo Delikatna magenta"),
    intArrayOf(219, 112, 147) to listOf("Blady Czerwień Fiołkowy", "Delikatnie różowy"),
    intArrayOf(150, 222, 209) to listOf("(eng) Pale Robin Egg Blue", "Bardzo delikatny cyjan"),
    intArrayOf(201, 192, 187) to listOf("Blade Srebro", "Szarawo-pomarańczowy"),
    intArrayOf(236, 235, 189) to listOf("(eng) Pale Spring Bud", "Jasny szarawo-żółty"),
    intArrayOf(188, 152, 126) to listOf("Blady Kreci", "Delikatnie desaturowany pomarańcz"),
    intArrayOf(219, 112, 147) to listOf("Blady Czerwień Fiołkowy", "Delikatnie różowy"),
    intArrayOf(120, 24, 74) to listOf("Bratkowy Fiolet", "Ciemny róż"),
    intArrayOf(255, 239, 213) to listOf("(eng) Papaya Whip", "Bardzo blady pomarańcz"),
    intArrayOf(80, 200, 120) to listOf("Paryski Zieleń", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(174, 198, 207) to listOf("Niebieski Pastelowy", "Grayish blue"),
    intArrayOf(131, 105, 83) to listOf("Brązowy Pastelowy", "Mocno desaturowana ciemna pomarańcza"),
    intArrayOf(207, 207, 196) to listOf("Szary Pastelowy", "Szarawożóły"),
    intArrayOf(119, 221, 119) to listOf("Zieleń Pastelowy", "Delikatny limonkowo zielony"),
    intArrayOf(244, 154, 194) to listOf("Pastelowa Magenta", "Bardzo delikatny różowy"),
    intArrayOf(255, 179, 71) to listOf("Pomarańcz Pastelowy", "Jasnopomarańczowy"),
    intArrayOf(255, 209, 220) to listOf("Róż Pastelowy", "Bardzo blady czerwony"),
    intArrayOf(179, 158, 181) to listOf("Fiolet Pastelowy", "Szarawa magenta"),
    intArrayOf(255, 105, 97) to listOf("Czerwień Pastelowy", "Jasnoczerwony"),
    intArrayOf(203, 153, 201) to listOf("Fiołkowy Pastel", "Szarawa magenta"),
    intArrayOf(253, 253, 150) to listOf("Żółty Pastelowy", "Bardzo delikatnie żółty"),
    intArrayOf(128, 0, 128) to listOf("(eng) Patriarch", "Ciemna magenta"),
    intArrayOf(83, 104, 120) to listOf("(eng) Payne Grey", "Mocno desaturowany Ciemnoniebieski"),
    intArrayOf(255, 229, 180) to listOf("Cielisty", "Blady pomarańcz"),
    intArrayOf(255, 218, 185) to listOf("(eng) Peach Puff", "Blady pomarańcz"),
    intArrayOf(250, 223, 173) to listOf("Cielisty Żółty", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(209, 226, 49) to listOf("Gruszka", "Jasnożółty"),
    intArrayOf(234, 224, 200) to listOf("Perłowy", "Jasny szarawo-pomarańczowy"),
    intArrayOf(136, 216, 192) to listOf("Perłowy Błękit Turkusowy", "Delikatnie desaturowany cyjan - limonkowo zielony"),
    intArrayOf(230, 226, 0) to listOf("Perydot", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(204, 204, 255) to listOf("Barwinek", "Bardzo blady niebieski"),
    intArrayOf(28, 57, 187) to listOf("Perski Niebieski", "Mocno niebieski"),
    intArrayOf(50, 18, 122) to listOf("Perski Indygo", "Ciemny fiołkowy"),
    intArrayOf(217, 144, 88) to listOf("Perski Pomarańcz", "Delikatny pomarańcz"),
    intArrayOf(247, 127, 190) to listOf("Perski Róż", "Delikatnie różowy"),
    intArrayOf(112, 28, 28) to listOf("Perska Śliwka", "Bardzo ciemny czerwień"),
    intArrayOf(204, 51, 51) to listOf("Perski Czerwień", "Mocno czerwony"),
    intArrayOf(254, 40, 162) to listOf("Perska Róża", "Jasnoróżowy"),
    intArrayOf(223, 0, 255) to listOf("Floks", "Czysta (lub prawie czysta) magenta"),
    intArrayOf(0, 15, 137) to listOf("Niebieska Ftalocyjanina", "Ciemnoniebieski"),
    intArrayOf(18, 53, 36) to listOf("Zielona Ftalocyjanina", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(253, 221, 230) to listOf("Świński Róż", "Jasny szaraworóżowy"),
    intArrayOf(1, 121, 111) to listOf("Zielony Sosnowy", "Ciemny cyjan"),
    intArrayOf(255, 192, 203) to listOf("Różowy", "Bardzo blady czerwony"),
    intArrayOf(252, 116, 253) to listOf("Różowy Flaming", "Delikatna magenta"),
    intArrayOf(247, 143, 167) to listOf("Różowy Sorbet", "Bardzo delikatnie czerwony"),
    intArrayOf(231, 172, 207) to listOf("Różowa Perła", "Bardzo delikatny różowy"),
    intArrayOf(147, 197, 114) to listOf("Pistacjowy", "Delikatnie desaturowany zieleń"),
    intArrayOf(229, 228, 226) to listOf("Platyna", "Jasny szarawo-pomarańczowy"),
    intArrayOf(221, 160, 221) to listOf("Śliwka", "Bardzo Delikatna magenta"),
    intArrayOf(255, 90, 54) to listOf("Czerwień Portlandu", "Jasnoczerwony"),
    intArrayOf(176, 224, 230) to listOf("Niebieski Proszkowy", "Bardzo delikatny cyjan"),
    intArrayOf(255, 143, 0) to listOf("Pomarańcz Princeton", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(0, 49, 83) to listOf("Pruski Niebieski", "Bardzo ciemnoniebieski"),
    intArrayOf(223, 0, 255) to listOf("Jaskrawy Fiolet", "Czysta (lub prawie czysta) magenta"),
    intArrayOf(204, 136, 153) to listOf("Brązowofioletowy", "Delikatnie desaturowany czerwony"),
    intArrayOf(255, 117, 24) to listOf("Dyniowy", "Jaskrawopomarańczowy"),
    intArrayOf(128, 0, 128) to listOf("Fioletowy", "Ciemna magenta"),
    intArrayOf(105, 53, 156) to listOf("Fioletowe Serce", "Ciemny umiarkowany fiołkowy"),
    intArrayOf(157, 129, 186) to listOf("(eng) Purple Mountain's Majesty", "Delikatnie desaturowany fiołkowy"),
    intArrayOf(150, 120, 182) to listOf("(wtf) Purple Mountain Majesty", "Delikatnie desaturowany fiołkowy"),
    intArrayOf(254, 78, 218) to listOf("Fioletowe Pizze", "Delikatna magenta"),
    intArrayOf(80, 64, 77) to listOf("Fioletowy Kreci", "Bardzo ciemna szarawa magenta"),
    intArrayOf(93, 138, 168) to listOf("(eng) Rackley", "Mocno desaturowany ciemnoniebieski"),
    intArrayOf(255, 53, 94) to listOf("(end) Radical Red", "Jasnoczerwony"),
    intArrayOf(227, 11, 93) to listOf("Malinowy", "Jaskraworóżowy"),
    intArrayOf(145, 95, 109) to listOf("Malinowy Lukier", "Mocno desaturowany Ciemny róż"),
    intArrayOf(226, 80, 152) to listOf("Malinowy Róż", "Delikatnie różowy"),
    intArrayOf(179, 68, 108) to listOf("Malinowa Róża", "Umiarkowany róż"),
    intArrayOf(214, 138, 89) to listOf("(eng) Raw Sienna", "Umiarkowany pomarańcz"),
    intArrayOf(255, 51, 204) to listOf("(eng) Razzle Dazzle Rose", "Jaskraworóżowy"),
    intArrayOf(227, 37, 107) to listOf("(eng) Razzmatazz", "Jasnoróżowy"),
    intArrayOf(255, 0, 0) to listOf("Czerwony", "Czysty (lub prawie czysty) czerwień"),
    intArrayOf(255, 83, 73) to listOf("Czerwonopomarańczowy", "Jasnoczerwony"),
    intArrayOf(165, 42, 42) to listOf("Czerwonobrązowy", "Ciemnoczerwony"),
    intArrayOf(199, 21, 133) to listOf("Czerwonofiołkowy", "Mocno różowy"),
    intArrayOf(0, 64, 64) to listOf("Głęboka Czerń", "Bardzo ciemny cyjan"),
    intArrayOf(215, 0, 64) to listOf("Głęboki Karmin", "Mocno różowy"),
    intArrayOf(8, 146, 208) to listOf("Głęboki Jaskrawoniebieski", "Mocno niebieski"),
    intArrayOf(182, 102, 210) to listOf("Głęboki Liliowy", "Bardzo ciemny cyjan"),
    intArrayOf(176, 48, 96) to listOf("Głęboki Wiśniowy", "Ciemny róż"),
    intArrayOf(65, 72, 51) to listOf("(eng) Rifle Green", "Bardzo ciemny szarawozielony"),
    intArrayOf(31, 206, 203) to listOf("(eng) Robin's Egg Blue", "Mocny cyjan"),
    intArrayOf(255, 0, 127) to listOf("Różany", "Czysty (lub prawie czysty) róż"),
    intArrayOf(249, 66, 158) to listOf("Różany Cukierek", "Jasnoróżowy"),
    intArrayOf(103, 72, 70) to listOf("Różany Heban", "Bardzo ciemny szarawoczerwony"),
    intArrayOf(183, 110, 121) to listOf("Różane Złoto", "Delikatnie desaturowany czerwony"),
    intArrayOf(227, 38, 54) to listOf("Różana Marzanna Barwieńska", "Jasnoczerwony"),
    intArrayOf(255, 102, 204) to listOf("Różany Róż", "Jasnorózowy"),
    intArrayOf(170, 152, 169) to listOf("Różany Kwarc", "Ciemna szarawa magenta"),
    intArrayOf(144, 93, 93) to listOf("Różany Kreci", "Mocno desaturowany ciemny czerwień"),
    intArrayOf(171, 78, 82) to listOf("Różana Dolina", "Ciemny umiarkowanie czerwony"),
    intArrayOf(101, 0, 11) to listOf("Palisander", "Bardzo ciemny czerwień"),
    intArrayOf(212, 0, 0) to listOf("(eng) Rosso Corsa", "Mocno czerwony"),
    intArrayOf(188, 143, 143) to listOf("(eng) Rosy Brown", "Szarawoczerwony"),
    intArrayOf(0, 56, 168) to listOf("Królewski Błękit", "Ciemnoniebieski"),
    intArrayOf(65, 105, 225) to listOf("Królewski Niebieski", "Jasnoniebieski"),
    intArrayOf(202, 44, 146) to listOf("Królewska Fuksja", "Mocno różowy"),
    intArrayOf(120, 81, 169) to listOf("Królewski Róż", "Ciemny umiarkowany fiołkowy"),
    intArrayOf(224, 17, 95) to listOf("Rubin", "Jaskraworóżowy"),
    intArrayOf(255, 0, 40) to listOf("Rumiany", "Czysty (lub prawie czysty) czerwień"),
    intArrayOf(187, 101, 40) to listOf("Rumiany Brązowy", "Mocno pomarańczowy"),
    intArrayOf(225, 142, 150) to listOf("Rumiany Różowy", "Bardzo delikatnie czerwony"),
    intArrayOf(168, 28, 7) to listOf("Czerwonawy", "Ciemnoczerwony"),
    intArrayOf(128, 70, 27) to listOf("Rudobrunatny", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(183, 65, 14) to listOf("Rdzawy", "Mocno pomarańczowy"),
    intArrayOf(0, 86, 63) to listOf("(eng) Sacramento State Green", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(139, 69, 19) to listOf("Brązowe Siodło", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(255, 103, 0) to listOf("(eng) Safety Orange", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(244, 196, 48) to listOf("Szafran", "Jasnożółty"),
    intArrayOf(35, 41, 122) to listOf("(eng) Saint Patrick Blue", "Ciemnoniebieski"),
    intArrayOf(255, 140, 105) to listOf("Łososiowy", "Bardzo jasnoczerwony"),
    intArrayOf(255, 145, 164) to listOf("Łososiowy Róż", "Bardzo jasnoczerwony"),
    intArrayOf(194, 178, 128) to listOf("Piasek", "Delikatnie desaturowany żółty"),
    intArrayOf(150, 113, 23) to listOf("Wydma Piaskowa", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(236, 213, 64) to listOf("Burza Piaskowa", "Jasnożółty"),
    intArrayOf(244, 164, 96) to listOf("Piaskowy Brąz", "Delikatny pomarańcz"),
    intArrayOf(150, 113, 23) to listOf("Kreci Piaskowy", "Ciemnopomarańczowy [Brązowy odcień]"),
    intArrayOf(80, 125, 42) to listOf("(eng) Sap Green", "Ciemny umiarkowny zieleń"),
    intArrayOf(15, 82, 186) to listOf("Szafirowy", "Mocno niebieski"),
    intArrayOf(203, 161, 53) to listOf("Złoty Połysk Atłasowy", "Umiarkowany pomarańcz"),
    intArrayOf(255, 36, 0) to listOf("Szkarłatny", "Czysty (lub prawie czysty) czerwień"),
    intArrayOf(255, 216, 0) to listOf("(eng) School Bus Yellow", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(118, 255, 122) to listOf("Krzykliwy Zieleń", "Bardzo jasny limonkowo zielony"),
    intArrayOf(0, 105, 148) to listOf("Błękit Morza", "Ciemnoniebieski"),
    intArrayOf(46, 139, 87) to listOf("Zieleń Morza", "Ciemny umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(50, 20, 20) to listOf("Skarogniady", "Bardzo ciemny (głównie czarny) czerwień"),
    intArrayOf(255, 245, 238) to listOf("Muszelka", "Bardzo blady (głównie biały) pomarańcz"),
    intArrayOf(255, 186, 0) to listOf("(eng) Selective Yellow", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(112, 66, 20) to listOf("Sepia", "Bardzo ciemny pomarańczowy [Brązowy odcień]"),
    intArrayOf(138, 121, 93) to listOf("Cień", "Mocno desaturowana ciemna pomarańcza"),
    intArrayOf(69, 206, 162) to listOf("Koniczyna", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(0, 158, 96) to listOf("Zieleń Koniczyny", "Ciemny cyjan - limonkowo zielony"),
    intArrayOf(252, 15, 192) to listOf("Wściekły Róż", "Jaskraworóżowy"),
    intArrayOf(136, 45, 23) to listOf("Sjena", "Ciemnoczerwony"),
    intArrayOf(192, 192, 192) to listOf("Srebrny", "Jasnoszary"),
    intArrayOf(203, 65, 11) to listOf("(eng) Sinopia", "Mocno pomarańczowy"),
    intArrayOf(0, 116, 116) to listOf("Skobeloff", "Ciemny cyjan"),
    intArrayOf(135, 206, 235) to listOf("Niebieski Średni", "Bardzo delikatny niebieski"),
    intArrayOf(207, 113, 175) to listOf("Magenta Średnia", "Delikatnie desaturowany róż"),
    intArrayOf(106, 90, 205) to listOf("Niebieski Łupek", "Umiarkowany niebieski"),
    intArrayOf(112, 128, 144) to listOf("Szary Łupek", "Ciemny szarawoniebieski"),
    intArrayOf(0, 51, 153) to listOf("Szkło Kobaltowe", "Ciemnoniebieski"),
    intArrayOf(147, 61, 65) to listOf("Przydymiony Topaz", "Ciemny umiarkowanie czerwony"),
    intArrayOf(16, 12, 8) to listOf("Przydymiona Czerń", "Bardzo ciemny (głównie czarny) pomarańczowy [Brązowy odcień]"),
    intArrayOf(255, 250, 250) to listOf("Śnieg", "Bardzo blady (głównie biały) czerwony"),
    intArrayOf(15, 192, 252) to listOf("(eng) Spiro Disco Ball", "Jaskrawoniebieski"),
    intArrayOf(167, 252, 0) to listOf("(eng) Spring Bud", "Czysty (lub prawie czysty) zieleń"),
    intArrayOf(0, 255, 127) to listOf("Wiosenna Zieleń", "Czysty (lub prawie czysty) cyjan - limonkowo zielony"),
    intArrayOf(70, 130, 180) to listOf("Niebieski Stalowy", "Umiarkowany niebieski"),
    intArrayOf(250, 218, 94) to listOf("(eng) Stil De Grain Yellow", "Delikatnie żółty"),
    intArrayOf(153, 0, 0) to listOf("(eng) Stizza", "Ciemnoczerwony"),
    intArrayOf(0, 128, 128) to listOf("Chmura Burzowa", "Ciemny cyjan"),
    intArrayOf(228, 217, 111) to listOf("Słomiany", "Delikatnie żółty"),
    intArrayOf(255, 204, 51) to listOf("Blask Słońca", "Jaskrawożóły"),
    intArrayOf(250, 214, 165) to listOf("Zachód Słońca", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(253, 94, 83) to listOf("Pomarańcz Zachodu Słońca", "Delikatnie czerwony"),
    intArrayOf(210, 180, 140) to listOf("Jasnobrązowy", "Delikatnie desaturowany pomarańcz"),
    intArrayOf(249, 77, 0) to listOf("Tangelo", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(242, 133, 0) to listOf("Mandarynka", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(255, 204, 0) to listOf("Mandarynkowo Żółty", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(72, 60, 50) to listOf("Kreci", "Bardzo ciemny szarawopomarańczowy"),
    intArrayOf(139, 133, 137) to listOf("Szary Kreci", "Ciemny szarawo-różowy"),
    intArrayOf(205, 87, 0) to listOf("Rudy", "Mocno pomarańczowy"),
    intArrayOf(208, 240, 192) to listOf("Zielony Herbaciany", "Bardzo delikatnie zielony"),
    intArrayOf(244, 194, 194) to listOf("Różany Herbaciany", "Bardzo delikatnie czerwony"),
    intArrayOf(0, 128, 128) to listOf("Morski", "Ciemny cyjan"),
    intArrayOf(54, 117, 136) to listOf("Morskoniebieski", "Ciemny umiarkowany cyjan"),
    intArrayOf(0, 109, 91) to listOf("Morskozielony", "Bardzo ciemny cyjan"),
    intArrayOf(226, 114, 91) to listOf("Terakota", "Delikatnie czerwony"),
    intArrayOf(216, 191, 216) to listOf("Oset", "Szarawa magenta"),
    intArrayOf(222, 111, 161) to listOf("(eng) Thulian Pink", "Delikatnie różowy"),
    intArrayOf(252, 137, 172) to listOf("(eng) Tickle Me Pink", "Delikatnie różowy"),
    intArrayOf(10, 186, 181) to listOf("(eng) Tiffany Blue", "Mocny cyjan"),
    intArrayOf(224, 141, 60) to listOf("Tygrysie Oko", "Bright orange"),
    intArrayOf(219, 215, 210) to listOf("Timberwolf", "Jasny szarawo-pomarańczowy"),
    intArrayOf(238, 230, 0) to listOf("Żółty Tytan", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(255, 99, 71) to listOf("Pomidor", "Jasnoczerwony"),
    intArrayOf(116, 108, 192) to listOf("(eng) Toolbox", "Delikatnie desaturowany niebieski"),
    intArrayOf(255, 200, 124) to listOf("Topaz", "Bardzo jasny pomarańczowy"),
    intArrayOf(253, 14, 53) to listOf("Czerwony Traktor", "Jaskrawoczerwony"),
    intArrayOf(128, 128, 128) to listOf("(eng) Trolley Grey", "Ciemnoszary"),
    intArrayOf(0, 117, 94) to listOf("Zwrotnikowy Las Deszczowy", "Ciemny cyjan"),
    intArrayOf(0, 115, 207) to listOf("(eng) True Blue", "Mocno niebieski"),
    intArrayOf(65, 125, 193) to listOf("Niebieski Pęk Kwiatów", "Umiarkowany niebieski"),
    intArrayOf(222, 170, 136) to listOf("Szarłat Biały", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(181, 114, 129) to listOf("Turecka Róża", "Delikatnie desaturowany czerwony"),
    intArrayOf(48, 213, 200) to listOf("Turkusowy", "Mocny cyjan"),
    intArrayOf(0, 255, 239) to listOf("Turkusowy Niebieski", "Czysty (lub prawie czysty) cyjan"),
    intArrayOf(160, 214, 180) to listOf("Turkusowa Zieleń", "Delikatnie desaturowany cyjan - limonkowo zielony"),
    intArrayOf(102, 66, 77) to listOf("Toskański Czerwień", "Bardzo ciemny desaturowany róż"),
    intArrayOf(138, 73, 107) to listOf("Lawendowy Zmierzch", "Ciemny umiarkowany róż"),
    intArrayOf(102, 2, 60) to listOf("Tyryjski Fiolet", "Bardzo ciemny róż"),
    intArrayOf(0, 51, 170) to listOf("(eng) UA Blue", "Ciemnoniebieski"),
    intArrayOf(217, 0, 76) to listOf("(eng) UA Red", "Czysty (lub prawie czysty) róż"),
    intArrayOf(83, 104, 149) to listOf("(eng) UCLA Blue", "Mocno desaturowany ciemnoniebieski"),
    intArrayOf(255, 179, 0) to listOf("(eng) UCLA Gold", "Czysty (lub prawie czysty) pomarańczowy"),
    intArrayOf(60, 208, 112) to listOf("Zielone UFO", "Umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(1, 68, 33) to listOf("(eng) UP Forest Green", "Bardzo ciemny cyjan - limonkowo zielony"),
    intArrayOf(123, 17, 19) to listOf("(eng) UP Maroon", "Ciemnoczerwony"),
    intArrayOf(153, 0, 0) to listOf("(eng) USC Cardinal", "Ciemnoczerwony"),
    intArrayOf(255, 204, 0) to listOf("(eng) USC Gold", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(136, 120, 195) to listOf("Pochrzyn Skrzydlaty", "Delikatnie desaturowany niebieski"),
    intArrayOf(255, 111, 255) to listOf("(eng) Ultra Pink", "Bardzo jasna magenta"),
    intArrayOf(18, 10, 143) to listOf("Ultramaryna", "Ciemnoniebieski"),
    intArrayOf(65, 102, 245) to listOf("Niebieska Ultramaryna", "Jasnoniebieski"),
    intArrayOf(99, 81, 71) to listOf("Umbra", "Bardzo ciemny szarawopomarańczowy"),
    intArrayOf(91, 146, 229) to listOf("Niebieski ONZ", "Delikatnie niebieski"),
    intArrayOf(183, 135, 39) to listOf("(eng) University Of California Gold", "Mocno pomarańczowy"),
    intArrayOf(255, 255, 102) to listOf("(eng) Unmellow Yellow", "Jasnożółty"),
    intArrayOf(174, 32, 41) to listOf("(eng) Upsdell Red", "Ciemnoczerwony"),
    intArrayOf(225, 173, 33) to listOf("Urobilin", "Jaskrawopomarańczowy"),
    intArrayOf(211, 0, 63) to listOf("(eng) Utah Crimson", "Mocno różowy"),
    intArrayOf(243, 229, 171) to listOf("Waniliowy", "Bardzo delikatnie żółty"),
    intArrayOf(197, 179, 88) to listOf("Złoty Vegas", "Umiarkowanie żółty"),
    intArrayOf(200, 8, 21) to listOf("Czerwień Wenecka", "Mocno czerwony"),
    intArrayOf(67, 179, 174) to listOf("Patyna", "Umiarkowany cyjan"),
    intArrayOf(227, 66, 52) to listOf("Czerwony Ceglasty", "Jasnoczerwony"),
    intArrayOf(160, 32, 240) to listOf("(eng) Veronica", "Jaskrawofiołkowy"),
    intArrayOf(238, 130, 238) to listOf("Fiołkowy", "Delikatna magenta"),
    intArrayOf(50, 74, 178) to listOf("Fiołkowy Błękit", "Ciemnoniebieski"),
    intArrayOf(247, 83, 148) to listOf("Fiołkowy Czerwień", "Delikatnie różowy"),
    intArrayOf(64, 130, 109) to listOf("Zieleń Chromowa", "Ciemny umiarkowany cyjan - limonkowo zielony"),
    intArrayOf(146, 39, 36) to listOf("Jaskrawy Kasztanowy", "Ciemnoczerwony"),
    intArrayOf(159, 29, 53) to listOf("Jaskrawy Burgund", "Ciemnoczerwony"),
    intArrayOf(218, 29, 129) to listOf("Jaskrawy Jasnoczerwony", "Jaskraworóżowy"),
    intArrayOf(255, 160, 137) to listOf("Jaskrawy Mandarynka", "Bardzo jasnoczerwony"),
    intArrayOf(159, 0, 255) to listOf("Jaskrawy Fiołkowy", "Czysty (lub prawie czysty) fiołkowy"),
    intArrayOf(0, 66, 66) to listOf("Ciepły Czarny", "Bardzo ciemny cyjan"),
    intArrayOf(0, 255, 255) to listOf("Błękit Turkusowy", "Czysty (lub prawie czysty) cyjan"),
    intArrayOf(100, 84, 82) to listOf("Wenge", "Bardzo ciemny szarawoczerwony"),
    intArrayOf(245, 222, 179) to listOf("Pszenica", "Bardzo delikatnie pomarańczowy"),
    intArrayOf(255, 255, 255) to listOf("Biały", "Biały"),
    intArrayOf(245, 245, 245) to listOf("Biały Dym", "Bardzo jasny szary (głównie biały)"),
    intArrayOf(255, 67, 164) to listOf("Poziomka", "Jasnorózowy"),
    intArrayOf(252, 108, 133) to listOf("Arbuz Dziczy", "Delikatnie czerwony"),
    intArrayOf(162, 173, 208) to listOf("Odległa Błękitna Planeta", "Szarawoniebieski"),
    intArrayOf(114, 47, 55) to listOf("Czerwone Wino", "Bardzo ciemny desaturowany czerwień"),
    intArrayOf(201, 160, 220) to listOf("Wisteria", "Bardzo delikatny fiołkowy"),
    intArrayOf(115, 134, 120) to listOf("Xanadu", "Ciemnoszary cyan - limonkowo zielony"),
    intArrayOf(15, 77, 146) to listOf("(eng) Yale Blue", "Ciemnoniebieski"),
    intArrayOf(255, 255, 0) to listOf("Żółty", "Czysty (lub prawie czysty) żóły"),
    intArrayOf(255, 174, 66) to listOf("Żółtopomarańczowy", "Jasnopomarańczowy"),
    intArrayOf(154, 205, 50) to listOf("Żółtozielony", "Mocno zielony"),
    intArrayOf(0, 20, 168) to listOf("Zaffre", "Ciemnoniebieski"),
    intArrayOf(44, 22, 8) to listOf("Brązowy Cynwaldyt", "Bardzo ciemny (głównie czarny) pomarańczowy [Brązowy odcień]"))
