package com.daltowacja.daltowacja

val advancedColors_pl = mapOf(intArrayOf(93, 138, 168) to listOf("Rackley", "Przeważnie desaturowany ciemnoniebieski"),
    intArrayOf(240, 248, 255) to listOf("Alice Blue", "Bardzo blady (głównie biały) niebieski"),
    intArrayOf(227, 38, 54) to listOf("Szalona Róża", "Jasny czerwony"),
    intArrayOf(239, 222, 205) to listOf("Migdałowy", "Jasno szaro-pomarańczowy"),
    intArrayOf(229, 43, 80) to listOf("Amarant ", "Jasny czerwony"),
    intArrayOf(255, 191, 0) to listOf("Fluorescencyjny Pomarańczowy", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(255, 3, 62) to listOf("Amerykańska Róża", "Żywe czerwone"),
    intArrayOf(153, 102, 204) to listOf("Ametystowy", "Umiarkowany fiolet"),
    intArrayOf(164, 198, 57) to listOf("Zielony Androidowy", "Umiarkowany żółty"),
    intArrayOf(242, 243, 244) to listOf("Munsell", "Jasnoszary niebieski"),
    intArrayOf(205, 149, 117) to listOf("Antyczny Mosiądz", "Lekko przesycona pomarańcza"),
    intArrayOf(145, 92, 131) to listOf("Antyczna Fuksja", "Przeważnie desaturowany ciemny róż"),
    intArrayOf(250, 235, 215) to listOf("Moccasin", "Jasno szaro-pomarańczowy"),
    intArrayOf(0, 128, 0) to listOf("Biurowa Zieleń", "Ciemna limonkowa zieleń"),
    intArrayOf(141, 182, 0) to listOf("Jasna Zieleń ", "Mocno żółty"),
    intArrayOf(251, 206, 177) to listOf("Morelowy", "Bardzo miękka pomarańcza"),
    intArrayOf(0, 255, 255) to listOf("Waterspout", "Czysty (lub w większości czysty) cyjan"),
    intArrayOf(127, 255, 212) to listOf("Akwamaryna", "Bardzo jasny cyjan - limonkowa zieleń"),
    intArrayOf(75, 83, 32) to listOf("Zielony Wojskowy", "Bardzo ciemnożółty (odcień oliwkowy)"),
    intArrayOf(233, 214, 107) to listOf("Hansa Yellow", "Miękki żółty"),
    intArrayOf(178, 190, 181) to listOf("Popiołowy", "Szarawy cyjan - limonkowa zieleń"),
    intArrayOf(135, 169, 107) to listOf("Szparagowy", "Przeważnie desaturowana ciemnozielona"),
    intArrayOf(255, 153, 102) to listOf("Mandarynkowy", "Jasnopomarańczowy"),
    intArrayOf(165, 42, 42) to listOf("Kasztanowy", "Ciemno czerwony"),
    intArrayOf(253, 238, 0) to listOf("Aureolin", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(110, 127, 128) to listOf("Aurometalsaurus", "Ciemnoszary cyjan"),
    intArrayOf(255, 32, 82) to listOf("Awesome", "Żywe czerwone"),
    intArrayOf(0, 127, 255) to listOf("Lazur", "Czysty (lub w większości czysty) niebieski"),
    intArrayOf(240, 255, 255) to listOf("Zamglony Lazur", "Bardzo blady (głównie biały) cyjan"),
    intArrayOf(137, 207, 240) to listOf("Jasnoniebieski ", "Bardzo miękki niebieski"),
    intArrayOf(161, 202, 241) to listOf("Jasnoniebieski", "Bardzo miękki niebieski"),
    intArrayOf(244, 194, 194) to listOf("Tea Rose", "Bardzo miękka czerwień"),
    intArrayOf(33, 171, 205) to listOf("Ball Blue", "Mocny cyjan"),
    intArrayOf(250, 231, 181) to listOf("Banana Mania", "Bardzo miękka pomarańcza"),
    intArrayOf(255, 225, 53) to listOf("Żółty Bananowy", "Jasny zółty"),
    intArrayOf(132, 132, 130) to listOf("Stalowoniebieski ", "Ciemnoszary żółty"),
    intArrayOf(152, 119, 123) to listOf("Bazaar", "Ciemnoszary czerwony"),
    intArrayOf(188, 212, 230) to listOf("Blady Wodny", "Jasnoszary niebieski"),
    intArrayOf(159, 129, 112) to listOf("Harcerski", "Przeważnie desaturowany ciemnopomarańczowy"),
    intArrayOf(245, 245, 220) to listOf("Beż ", "Jasnoszary żółtawy"),
    intArrayOf(255, 228, 196) to listOf("Zupa Ze Skorupiaków", "Bardzo blady pomarańczowy"),
    intArrayOf(61, 43, 31) to listOf("Bistrowy", "Bardzo ciemna desaturowana pomarańcza"),
    intArrayOf(254, 111, 94) to listOf("Bittersweet", "Miękka czerwień"),
    intArrayOf(0, 0, 0) to listOf("Czarny", "Czarny"),
    intArrayOf(255, 235, 205) to listOf("Blanszowane Migdały", "Bardzo blady pomarańczowy"),
    intArrayOf(49, 140, 231) to listOf("Niebieski Francuski", "Jasnoniebieski"),
    intArrayOf(172, 229, 238) to listOf("Śnieżny Niebieski", "Bardzo delikatny cyjan"),
    intArrayOf(250, 240, 190) to listOf("Blond", "Bardzo delikatny żółty"),
    intArrayOf(0, 0, 255) to listOf("Niebieski", "Czysty (lub w większości czysty) niebieski"),
    intArrayOf(162, 162, 208) to listOf("Blue Bell", "Szaroniebieski"),
    intArrayOf(102, 153, 204) to listOf("Blue Gray", "Umiarkowany niebieski"),
    intArrayOf(13, 152, 186) to listOf("Morska Zieleń ", "Mocny cyjan"),
    intArrayOf(138, 43, 226) to listOf("Blue Violet", "Jasny fiolet"),
    intArrayOf(222, 93, 131) to listOf("Blush", "Delikatny róż"),
    intArrayOf(121, 68, 59) to listOf("Bole", "Ciemna umiarkowana czerwień"),
    intArrayOf(0, 149, 182) to listOf("Bondi Blue", "Mocny cyjan"),
    intArrayOf(227, 218, 201) to listOf("Kościany", "Jasno szaro-pomarańczowy"),
    intArrayOf(204, 0, 0) to listOf("Boston University Red", "Mocna czerwień"),
    intArrayOf(0, 106, 78) to listOf("Butelkowo Zielony", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(135, 50, 96) to listOf("Malinojeżynowy", "Ciemny umiarkowany róż"),
    intArrayOf(0, 112, 255) to listOf("Brandeis Blue", "Czysty (lub w większości czysty) niebieski"),
    intArrayOf(181, 166, 66) to listOf("Mosiężny", "Umiarkowany żółty"),
    intArrayOf(203, 65, 84) to listOf("Ceglastoczerwony ", "Umiarkowana czerwień"),
    intArrayOf(29, 172, 214) to listOf("Jasny Modry", "Mocny cyjan"),
    intArrayOf(102, 255, 0) to listOf("Jaskrawo Zielony ", "Czysta (lub w większości czysta) zieleń"),
    intArrayOf(191, 148, 228) to listOf("Jasna Lawenda", "Bardzo delikatny fiolet"),
    intArrayOf(195, 33, 72) to listOf("Jasny Bordowy", "Mocna czerwień"),
    intArrayOf(255, 0, 127) to listOf("Róża", "Czysty (lub w większości czysty) róż"),
    intArrayOf(8, 232, 222) to listOf("Jasny Turkus", "Żywy cyjan"),
    intArrayOf(209, 159, 232) to listOf("Bright Ube", "Bardzo delikatny fiolet"),
    intArrayOf(244, 187, 255) to listOf("Elektryczna Lawenda", "Jasnopurpurowy"),
    intArrayOf(255, 85, 163) to listOf("Brilliant Rose", "Jasnoróżowy"),
    intArrayOf(251, 96, 127) to listOf("Skrajny Różowy", "Miękka czerwień"),
    intArrayOf(0, 66, 37) to listOf("British Racing Green", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(205, 127, 50) to listOf("Brąz", "Mocna pomarańcza"),
    intArrayOf(255, 193, 204) to listOf("Guma Balonowa", "Bardzo bladoczerwony"),
    intArrayOf(231, 254, 255) to listOf("Bubbles", "Bardzo blady (głównie biały) cyjan"),
    intArrayOf(240, 220, 130) to listOf("Buff", "Miękki żółty"),
    intArrayOf(72, 6, 7) to listOf("Róża Bułgarska", "Bardzo ciemnoczerwony"),
    intArrayOf(128, 0, 32) to listOf("Burgundy", "Ciemno czerwony"),
    intArrayOf(222, 184, 135) to listOf("Burlywood", "Bardzo miękka pomarańcza"),
    intArrayOf(204, 85, 0) to listOf("Palona Pomarańcza", "Mocna pomarańcza"),
    intArrayOf(233, 116, 81) to listOf("Sjena Palona ", "Miękka czerwień"),
    intArrayOf(138, 51, 36) to listOf("Umbra Palona ", "Ciemno czerwony"),
    intArrayOf(189, 51, 164) to listOf("Byzantine", "Umiarkowana magenta"),
    intArrayOf(112, 41, 99) to listOf("Byzantium", "Bardzo ciemny magenta"),
    intArrayOf(0, 122, 165) to listOf("Niebieski Cg", "Ciemny niebieski"),
    intArrayOf(224, 60, 49) to listOf("Czerwony Cg", "Jasny czerwony"),
    intArrayOf(83, 104, 114) to listOf("Cadet", "Bardzo ciemny szaro niebieski"),
    intArrayOf(95, 158, 160) to listOf("Niebieski Z Odcieniem Szarego ", "Przeważnie desaturowany ciemny cyjan"),
    intArrayOf(145, 163, 176) to listOf("Cadet Grey", "Ciemnoszary niebieski"),
    intArrayOf(0, 107, 60) to listOf("Zielony Kadmowy", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(237, 135, 45) to listOf("Pomarańczowy Kadmowy", "Jasno pomarańczowy"),
    intArrayOf(227, 0, 34) to listOf("Czerwony Kadmowy", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(255, 246, 0) to listOf("Zółty Kadmowy", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(166, 123, 91) to listOf("Francuski Beż", "Ciemny umiarkowany pomarańczowy"),
    intArrayOf(75, 54, 33) to listOf("Café Noir", "Bardzo ciemna desaturowana pomarańcza"),
    intArrayOf(30, 77, 43) to listOf("Cal Poly Pomona Green", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(163, 193, 173) to listOf("Jasny Błękit ", "Szarawy cyjan - limonkowa zieleń"),
    intArrayOf(193, 154, 107) to listOf("Lion", "Lekko przesycona pomarańcza"),
    intArrayOf(120, 134, 107) to listOf("Camouflage Green", "Ciemno szaro zielony"),
    intArrayOf(255, 255, 153) to listOf("Kanarkowy", "Bardzo jasnożółty"),
    intArrayOf(255, 239, 0) to listOf("Kanarkowy", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(255, 8, 0) to listOf("Słodkie Czerwona Jabłko", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(228, 113, 122) to listOf("Cukierkowy Róż", "Miękka czerwień"),
    intArrayOf(0, 191, 255) to listOf("Głęboki Błękit Nieba", "Czysty (lub w większości czysty) niebieski"),
    intArrayOf(89, 39, 32) to listOf("Caput Mortuum", "Bardzo ciemnoczerwony"),
    intArrayOf(196, 30, 58) to listOf("Cardinal", "Mocna czerwień"),
    intArrayOf(0, 204, 153) to listOf("Zielony Karaibski", "Mocny cyjan"),
    intArrayOf(255, 0, 64) to listOf("Karminowy", "Czysty (lub w większości czysty) róż"),
    intArrayOf(235, 76, 66) to listOf("Różowy Karminowy", "Jasny czerwony"),
    intArrayOf(255, 0, 56) to listOf("Czerwony Karminowy", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(255, 166, 201) to listOf("Carnation Pink", "Blady różowy"),
    intArrayOf(179, 27, 27) to listOf("Cornell Red", "Mocna czerwień"),
    intArrayOf(153, 186, 221) to listOf("Carolina Blue", "Bardzo miękki niebieski"),
    intArrayOf(237, 145, 33) to listOf("Pomarańczowy Marchewkowy", "Żywy pomarańczowy"),
    intArrayOf(172, 225, 175) to listOf("Seledyn ", "Bardzo miękka limonkowa zieleń"),
    intArrayOf(178, 255, 255) to listOf("Selina", "Blady cyjan"),
    intArrayOf(73, 151, 208) to listOf("Niebiański Niebieski", "Umiarkowany niebieski"),
    intArrayOf(222, 49, 99) to listOf("Wiśniowy", "Jasnoróżowy"),
    intArrayOf(236, 59, 131) to listOf("Cerise Pink", "Jasnoróżowy"),
    intArrayOf(0, 123, 167) to listOf("Modry ", "Ciemny niebieski"),
    intArrayOf(42, 82, 190) to listOf("Modry Błękitny ", "Mocny niebieski"),
    intArrayOf(160, 120, 90) to listOf("Chamoisee", "Przeważnie desaturowany ciemnopomarańczowy"),
    intArrayOf(250, 214, 165) to listOf("Zachód Słońca", "Bardzo miękka pomarańcza"),
    intArrayOf(54, 69, 79) to listOf("Węgiel Drzewny ", "Bardzo ciemny szaro niebieski"),
    intArrayOf(127, 255, 0) to listOf("Chartreuse", "Czysta (lub w większości czysta) zieleń"),
    intArrayOf(255, 183, 197) to listOf("Kwiat Wiśni", "Jasnoczerwony"),
    intArrayOf(205, 92, 92) to listOf("Indyjska Czerwień", "Umiarkowana czerwień"),
    intArrayOf(210, 105, 30) to listOf("Kakaowy", "Mocna pomarańcza"),
    intArrayOf(255, 167, 0) to listOf("Żółcień Chromowa ", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(152, 129, 123) to listOf("Popielaty", "Ciemnoszary czerwony"),
    intArrayOf(227, 66, 52) to listOf("Vermilion", "Jasny czerwony"),
    intArrayOf(228, 208, 10) to listOf("Cytryn ", "Żywy żółty"),
    intArrayOf(251, 204, 231) to listOf("Classic Rose", "Jasnoszary róż"),
    intArrayOf(0, 71, 171) to listOf("Kobaltowy", "Ciemny niebieski"),
    intArrayOf(111, 78, 55) to listOf("Kawowy", "Bardzo ciemna desaturowana pomarańcza"),
    intArrayOf(155, 221, 255) to listOf("Columbia Blue", "Jasnoniebieskie"),
    intArrayOf(0, 46, 99) to listOf("Cool Black", "Bardzo ciemnoniebieski"),
    intArrayOf(140, 146, 172) to listOf("Cool Grey", "Ciemnoszary niebieski"),
    intArrayOf(184, 115, 51) to listOf("Miedziany", "Umiarkowany pomarańczowy"),
    intArrayOf(153, 102, 102) to listOf("Copper Rose", "Przeważnie desaturowana ciemna czerwień"),
    intArrayOf(255, 56, 0) to listOf("Coquelicot", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(255, 127, 80) to listOf("Koralowy", "Jasnopomarańczowy"),
    intArrayOf(248, 131, 121) to listOf("Róż Koralowy ", "Miękka czerwień"),
    intArrayOf(255, 64, 64) to listOf("Koralowy Czerwony", "Jasnoczerwony"),
    intArrayOf(137, 63, 69) to listOf("Cordovan", "Ciemna umiarkowana czerwień"),
    intArrayOf(251, 236, 93) to listOf("Kukurydziany", "Miękki żółty"),
    intArrayOf(154, 206, 235) to listOf("Chabrowy ", "Bardzo miękki niebieski"),
    intArrayOf(100, 149, 237) to listOf("Chabrowy Niebieski", "Miękki niebieski"),
    intArrayOf(255, 248, 220) to listOf("Cornsilk", "Bardzo jasnożółty"),
    intArrayOf(255, 248, 231) to listOf("Cosmic Latte", "Bardzo blady (głównie biały) pomarańczowy"),
    intArrayOf(255, 188, 217) to listOf("Wata Cukrowa", "Blady różowy"),
    intArrayOf(255, 253, 208) to listOf("Śmietankowy", "Bardzo jasnożółty"),
    intArrayOf(220, 20, 60) to listOf("Pąsowy ", "Żywe czerwone"),
    intArrayOf(153, 0, 0) to listOf("Usc Cardinal", "Ciemno czerwony"),
    intArrayOf(190, 0, 50) to listOf("Crimson Glory", "Mocny róż"),
    intArrayOf(255, 255, 49) to listOf("Daffodil", "Żywy żółty"),
    intArrayOf(240, 225, 48) to listOf("Dandelion", "Jasny żółty"),
    intArrayOf(0, 0, 139) to listOf("Ciemnoniebieski", "Ciemny niebieski"),
    intArrayOf(101, 67, 33) to listOf("Otter Brown", "Bardzo ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(93, 57, 84) to listOf("Dark Byzantium", "Bardzo ciemna, nienasycona magenta"),
    intArrayOf(164, 0, 0) to listOf("Dark Candy Apple Red", "Ciemno czerwony"),
    intArrayOf(8, 69, 126) to listOf("Dark Cerulean", "Ciemny niebieski"),
    intArrayOf(152, 105, 96) to listOf("Ciemny Kasztan", "Przeważnie desaturowana ciemna czerwień"),
    intArrayOf(205, 91, 69) to listOf("Ciemny Koral", "Umiarkowana czerwień"),
    intArrayOf(0, 139, 139) to listOf("Ciemny Cyjan", "Ciemny cyjan"),
    intArrayOf(83, 104, 120) to listOf("Payne Grey", "Przeważnie desaturowany ciemnoniebieski"),
    intArrayOf(184, 134, 11) to listOf("Dark Goldenrod", "Mocna pomarańcza"),
    intArrayOf(169, 169, 169) to listOf("Ciemny Szary", "Szary"),
    intArrayOf(1, 50, 32) to listOf("Ciemnozielony", "Bardzo ciemny (głównie czarny) cyjan - limonkowa zieleń"),
    intArrayOf(26, 36, 33) to listOf("Ciemna Zieleń Dżungli", "Bardzo ciemny (głównie czarny) cyjan - limonkowa zieleń"),
    intArrayOf(189, 183, 107) to listOf("Ciemny Khaki", "Lekko przesycona żółć"),
    intArrayOf(72, 60, 50) to listOf("Szarobrązowy", "Bardzo ciemny szaro-pomarańczowy"),
    intArrayOf(115, 79, 150) to listOf("Ciemna Lawenda", "Ciemny umiarkowany fiolet"),
    intArrayOf(139, 0, 139) to listOf("Ciemna Magenta", "Ciemna magenta"),
    intArrayOf(0, 51, 102) to listOf("Dark Midnight Blue", "Bardzo ciemnoniebieski"),
    intArrayOf(85, 107, 47) to listOf("Ciemna Oliwkowa Zieleń", "Bardzo ciemna desaturowana zieleń"),
    intArrayOf(255, 140, 0) to listOf("Ciemna Pomarańcza", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(153, 50, 204) to listOf("Ciemna Orchidea", "Mocny fiolet"),
    intArrayOf(119, 158, 203) to listOf("Ciemny Pastelowy Niebieski", "Lekko przesycony niebieski"),
    intArrayOf(3, 192, 60) to listOf("Ciemna Pastelowa Zieleń", "Mocny cyjan - limonkowa zieleń"),
    intArrayOf(150, 111, 214) to listOf("Ciemny Pastelowy Fiolet", "Lekko przyciemniony fiolet"),
    intArrayOf(194, 59, 34) to listOf("Ciemna Pastelowa Czerwień", "Mocna czerwień"),
    intArrayOf(231, 84, 128) to listOf("Ciemno Różowy", "Delikatny róż"),
    intArrayOf(0, 51, 153) to listOf("Smalt", "Ciemny niebieski"),
    intArrayOf(135, 38, 87) to listOf("Ciemna Malina", "Ciemno różowy"),
    intArrayOf(139, 0, 0) to listOf("Ciemno Czerwony", "Ciemno czerwony"),
    intArrayOf(233, 150, 122) to listOf("Ciemny Łosoś", "Miękki pomarańczowy"),
    intArrayOf(86, 3, 25) to listOf("Ciemny Szkarłat", "Bardzo ciemny róż"),
    intArrayOf(143, 188, 143) to listOf("Ciemna Morska Zieleń", "Szaro-limonkowa zieleń"),
    intArrayOf(60, 20, 20) to listOf("Ciemna Sienna", "Bardzo ciemnoczerwony"),
    intArrayOf(72, 61, 139) to listOf("Dark Slate Blue", "Ciemny umiarkowany niebieski"),
    intArrayOf(47, 79, 79) to listOf("Dark Slate Gray", "Bardzo ciemny desaturowany cyjan"),
    intArrayOf(23, 114, 69) to listOf("Ciemna Wiosenna Zieleń", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(145, 129, 81) to listOf("Ciemna Opalenizna", "Przeważnie desaturowany ciemnożółty"),
    intArrayOf(255, 168, 18) to listOf("Ciemna Mandarynka", "Żywy pomarańczowy"),
    intArrayOf(204, 78, 92) to listOf("Ciemna Terakota", "Umiarkowana czerwień"),
    intArrayOf(0, 206, 209) to listOf("Ciemny Turkus", "Mocny cyjan"),
    intArrayOf(148, 0, 211) to listOf("Ciemny Fiolet", "Mocny fiolet"),
    intArrayOf(0, 105, 62) to listOf("Dartmouth Green", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(85, 85, 85) to listOf("Davy Grey", "Bardzo ciemny szary"),
    intArrayOf(215, 10, 83) to listOf("Debian Red", "Mocny róż"),
    intArrayOf(169, 32, 62) to listOf("Głęboki Karmin", "Ciemno czerwony"),
    intArrayOf(239, 48, 56) to listOf("Głęboki Karminowy Róż", "Jasny czerwony"),
    intArrayOf(233, 105, 44) to listOf("Głęboka Marchwiowa Pomarańcza", "Jasno pomarańczowy"),
    intArrayOf(218, 50, 135) to listOf("Głęboka Wiśnia", "Jasnoróżowy"),
    intArrayOf(185, 78, 72) to listOf("Głęboki Kasztan", "Umiarkowana czerwień"),
    intArrayOf(112, 66, 65) to listOf("Głęboka Kawa", "Bardzo ciemna desaturowana czerwień"),
    intArrayOf(193, 84, 193) to listOf("Głęboka Fuksja", "Umiarkowana magenta"),
    intArrayOf(0, 75, 73) to listOf("Głęboka Zieleń Dżungli", "Bardzo ciemny cyjan"),
    intArrayOf(153, 85, 187) to listOf("Głęboki Liliowy", "Umiarkowany fiolet"),
    intArrayOf(204, 0, 204) to listOf("Głęboka Magenta", "Mocna magenta"),
    intArrayOf(255, 203, 164) to listOf("Głęboka Brzoskwinia", "Jasnopomarańczowy"),
    intArrayOf(255, 20, 147) to listOf("Fluorescencyjny Różowy", "Żywy róż"),
    intArrayOf(255, 153, 51) to listOf("Głęboki Szafran", "Żywy pomarańczowy"),
    intArrayOf(21, 96, 189) to listOf("Dżinsowy", "Mocny niebieski"),
    intArrayOf(237, 201, 175) to listOf("Pustynny Piach", "Bardzo miękka pomarańcza"),
    intArrayOf(105, 105, 105) to listOf("Przyćmiony Szary", "Bardzo ciemny szary"),
    intArrayOf(30, 144, 255) to listOf("Dodger Blue", "Żywy niebieski"),
    intArrayOf(215, 24, 104) to listOf("Róża Dereniowa", "Mocny róż"),
    intArrayOf(133, 187, 101) to listOf("Dolarowy", "Lekko przesycona zieleń"),
    intArrayOf(150, 113, 23) to listOf("Sandy Taupe", "Ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(0, 0, 156) to listOf("Duke Blue", "Ciemny niebieski"),
    intArrayOf(225, 169, 95) to listOf("Ziemisty Żółty", "Miękki pomarańczowy"),
    intArrayOf(194, 178, 128) to listOf("Sand", "Lekko przesycona żółć"),
    intArrayOf(97, 64, 81) to listOf("Eggplant", "Bardzo ciemny szaro-różowy"),
    intArrayOf(240, 234, 214) to listOf("Jasnożółty ", "Jasnoszary żółtawy"),
    intArrayOf(16, 52, 166) to listOf("Egipski Niebieski", "Ciemny niebieski"),
    intArrayOf(125, 249, 255) to listOf("Jaskrawoniebieski ", "Bardzo jasny cyjan"),
    intArrayOf(255, 0, 63) to listOf("Elektryczny Szkarłat", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(0, 255, 0) to listOf("Zielony", "Czysta (lub w większości czysta) limonkowa zieleń"),
    intArrayOf(111, 0, 255) to listOf("Elektryczny Indygo", "Czysty (lub w większości czysty) fiolet"),
    intArrayOf(204, 255, 0) to listOf("Fluorescencyjny Żółty", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(191, 0, 255) to listOf("Elektryczny Fiolet", "Czysty (lub w większości czysty) fiolet"),
    intArrayOf(63, 0, 255) to listOf("Elektryczna Ultramaryna", "Czysty (lub w większości czysty) niebieski"),
    intArrayOf(143, 0, 255) to listOf("Elektryczny Fiolet", "Czysty (lub w większości czysty) fiolet"),
    intArrayOf(255, 255, 0) to listOf("Żółty", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(80, 200, 120) to listOf("Zieleń Paryska", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(150, 200, 162) to listOf("Eton Blue", "Szaro-limonkowa zieleń"),
    intArrayOf(128, 24, 24) to listOf("Czerwień Faluńska ", "Ciemno czerwony"),
    intArrayOf(255, 0, 255) to listOf("Magenta", "Czysta (lub w większości czysta) magenta"),
    intArrayOf(181, 51, 137) to listOf("Fandango", "Umiarkowany róż"),
    intArrayOf(244, 0, 161) to listOf("Hollywood Cerise", "Czysty (lub w większości czysty) róż"),
    intArrayOf(229, 170, 112) to listOf("Jelonkowy", "Miękki pomarańczowy"),
    intArrayOf(77, 93, 83) to listOf("Polowa Szarość", "Bardzo ciemny szaro cyjan - limonkowa zieleń"),
    intArrayOf(113, 188, 120) to listOf("Paproć", "Lekko desaturowana limonkowa zieleń"),
    intArrayOf(79, 121, 66) to listOf("Zielona Paproć", "Ciemna umiarkowana limonkowa zieleń"),
    intArrayOf(255, 40, 0) to listOf("Czerwony Ferrari", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(108, 84, 30) to listOf("Field Drab", "Bardzo ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(206, 32, 41) to listOf("Fire Engine Red", "Mocna czerwień"),
    intArrayOf(178, 34, 34) to listOf("Firebrick", "Ciemno czerwony"),
    intArrayOf(226, 88, 34) to listOf("Płomienny", "Jasno pomarańczowy"),
    intArrayOf(252, 142, 172) to listOf("Flamingo Pink", "Bardzo delikatny róż"),
    intArrayOf(247, 233, 142) to listOf("Żółtawy ", "Bardzo delikatny żółty"),
    intArrayOf(238, 220, 130) to listOf("Flax", "Miękki żółty"),
    intArrayOf(255, 250, 240) to listOf("Kwiatowy Biały", "Bardzo blady (głównie biały) pomarańczowy"),
    intArrayOf(255, 0, 79) to listOf("Folly", "Czysty (lub w większości czysty) róż"),
    intArrayOf(34, 139, 34) to listOf("Zielony Las", "Ciemna limonkowa zieleń"),
    intArrayOf(0, 114, 187) to listOf("Francuski Niebieski", "Mocny niebieski"),
    intArrayOf(134, 96, 142) to listOf("Francuski Liliowy", "Przeważnie desaturowana ciemna magenta"),
    intArrayOf(246, 74, 138) to listOf("Francuska Róża", "Delikatny róż"),
    intArrayOf(255, 119, 255) to listOf("Fuksjowy Róż", "Bardzo jasna magenta"),
    intArrayOf(228, 132, 0) to listOf("Zółtobrązowy", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(204, 102, 102) to listOf("Fuzzy Wuzzy", "Umiarkowana czerwień"),
    intArrayOf(220, 220, 220) to listOf("Gainsboro", "Bardzo jasny szary"),
    intArrayOf(228, 155, 15) to listOf("Gamboge", "Żywy pomarańczowy"),
    intArrayOf(248, 248, 255) to listOf("Biały Duch", "Bardzo blady (głównie biały) niebieski"),
    intArrayOf(176, 101, 0) to listOf("Rudy", "Ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(96, 130, 182) to listOf("Zielonkawoniebieski ", "Lekko przesycony niebieski"),
    intArrayOf(230, 232, 250) to listOf("Glitter", "Jasnoszary niebieski"),
    intArrayOf(255, 215, 0) to listOf("Złocisty ", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(153, 101, 21) to listOf("Złocistobrązowy ", "Ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(252, 194, 0) to listOf("Golden Poppy", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(255, 223, 0) to listOf("Złocistożółty ", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(218, 165, 32) to listOf("Goldenrod", "Żywy pomarańczowy"),
    intArrayOf(168, 228, 160) to listOf("Granny Smith Apple", "Bardzo miękka limonkowa zieleń"),
    intArrayOf(128, 128, 128) to listOf("Trolley Grey", "Ciemny szary"),
    intArrayOf(70, 89, 69) to listOf("Szare Szparagi", "Bardzo ciemny szaro-limonkowy"),
    intArrayOf(17, 100, 180) to listOf("Zielono-Niebieski", "Mocny niebieski"),
    intArrayOf(173, 255, 47) to listOf("Zielony Żółty", "Żywa zieleń"),
    intArrayOf(169, 154, 134) to listOf("Grullo", "Ciemno szaro-pomarańczowy"),
    intArrayOf(0, 255, 127) to listOf("Wiosenna Zieleń", "Czysty (lub w większości czysty) cyjan - limonkowa zieleń"),
    intArrayOf(102, 56, 84) to listOf("Halayà  Úbe", "Bardzo ciemny, przygaszony róż"),
    intArrayOf(68, 108, 207) to listOf("Han Blue", "Umiarkowany niebieski"),
    intArrayOf(82, 24, 250) to listOf("Han Purple", "Żywy fiolet"),
    intArrayOf(63, 255, 0) to listOf("Harlequin", "Czysta (lub w większości czysta) limonkowa zieleń"),
    intArrayOf(201, 0, 22) to listOf("Harvard Crimson", "Mocna czerwień"),
    intArrayOf(218, 145, 0) to listOf("Harvest Gold", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(128, 128, 0) to listOf("Olive", "Ciemnożółty (odcień oliwki)"),
    intArrayOf(223, 115, 255) to listOf("Heliotrope", "Bardzo jasna magenta"),
    intArrayOf(240, 255, 240) to listOf("Spadźowy", "Bardzo blady (głównie biały) limonkowy"),
    intArrayOf(73, 121, 107) to listOf("Zieleń Prostytutki", "Przeważnie desaturowany ciemny cyjan - limonkowa zieleń"),
    intArrayOf(255, 29, 206) to listOf("Gorąca Magenta", "Żywa magenta"),
    intArrayOf(255, 105, 180) to listOf("Gorący Róż", "Bardzo jasny róż"),
    intArrayOf(53, 94, 59) to listOf("Zielony Łowiecki", "Bardzo ciemna desaturowana limonkowa zieleń"),
    intArrayOf(252, 247, 94) to listOf("Icterine", "Miękki żółty"),
    intArrayOf(178, 236, 93) to listOf("Inchworm", "Miękki zielony"),
    intArrayOf(19, 136, 8) to listOf("India Green", "Ciemna limonkowa zieleń"),
    intArrayOf(227, 168, 87) to listOf("Indyjski Żółty", "Miękki pomarańczowy"),
    intArrayOf(75, 0, 130) to listOf("Indygo", "Ciemny fiolet"),
    intArrayOf(0, 47, 167) to listOf("International Klein Blue", "Ciemny niebieski"),
    intArrayOf(255, 79, 0) to listOf("International Orange", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(90, 79, 207) to listOf("Irys", "Umiarkowany niebieski"),
    intArrayOf(244, 240, 236) to listOf("Isabelline", "Jasno szaro-pomarańczowy"),
    intArrayOf(0, 144, 0) to listOf("Islamska Zieleń", "Ciemna limonkowa zieleń"),
    intArrayOf(255, 255, 240) to listOf("Kość Słoniowa", "Bardzo blady (przeważnie biały) żółty"),
    intArrayOf(0, 168, 107) to listOf("Jade", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(248, 222, 126) to listOf("Jaśminowy", "Miękki żółty"),
    intArrayOf(215, 59, 62) to listOf("Jasper", "Umiarkowana czerwień"),
    intArrayOf(165, 11, 94) to listOf("Jazzberry Jam", "Ciemno różowy"),
    intArrayOf(250, 218, 94) to listOf("Stil De Grain Yellow", "Miękki żółty"),
    intArrayOf(189, 218, 87) to listOf("June Bud", "Miękki żółty"),
    intArrayOf(41, 171, 135) to listOf("Zielona Dżungla", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(232, 0, 13) to listOf("Ku Crimson", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(76, 187, 23) to listOf("Jasny Żółto-Zielony ", "Mocna zieleń"),
    intArrayOf(195, 176, 145) to listOf("Khaki", "Lekko przesycona pomarańcza"),
    intArrayOf(8, 120, 48) to listOf("La Salle Green", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(214, 202, 221) to listOf("Languid Lavender", "Jasnoszary fiolet"),
    intArrayOf(38, 97, 156) to listOf("Lapis Lazuli", "Ciemny niebieski"),
    intArrayOf(254, 254, 34) to listOf("Laser Lemon", "Żywy żółty"),
    intArrayOf(169, 186, 157) to listOf("Laurel Green", "Szaro zielony"),
    intArrayOf(207, 16, 32) to listOf("Lawa", "Mocna czerwień"),
    intArrayOf(230, 230, 250) to listOf("Mgiełka Lawendowa", "Jasnoszary niebieski"),
    intArrayOf(204, 204, 255) to listOf("Periwinkle", "Bardzo jasnoniebieski"),
    intArrayOf(255, 240, 245) to listOf("Lavender Blush", "Bardzo blady (głównie biały) róż"),
    intArrayOf(196, 195, 208) to listOf("Lawendowy Szary", "Szaroniebieski"),
    intArrayOf(148, 87, 235) to listOf("Lawenda Indygo", "Miękki fiolet"),
    intArrayOf(238, 130, 238) to listOf("Fioletowy", "Miękka magenta"),
    intArrayOf(251, 174, 210) to listOf("Lawendowy Róż", "Bardzo delikatny róż"),
    intArrayOf(150, 123, 182) to listOf("Lawendowy Fiolet", "Lekko przyciemniony fiolet"),
    intArrayOf(251, 160, 227) to listOf("Lavender Rose", "Bardzo delikatny róż"),
    intArrayOf(124, 252, 0) to listOf("Zielony Trawnikowy", "Czysta (lub w większości czysta) zieleń"),
    intArrayOf(255, 247, 0) to listOf("Cytryna", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(255, 244, 79) to listOf("Cytrynowy", "Jasny zółty"),
    intArrayOf(255, 250, 205) to listOf("Lemon Chiffon", "Bardzo jasnożółty"),
    intArrayOf(191, 255, 0) to listOf("Limonkowy", "Czysta (lub w większości czysta) zieleń"),
    intArrayOf(245, 105, 145) to listOf("Jasny Karmazyn", "Delikatny róż"),
    intArrayOf(230, 143, 172) to listOf("Jasny Róż Thulian", "Bardzo delikatny róż"),
    intArrayOf(253, 213, 177) to listOf("Cytrynowy", "Bardzo miękka pomarańcza"),
    intArrayOf(173, 216, 230) to listOf("Jasny Niebieski", "Bardzo delikatny cyjan"),
    intArrayOf(181, 101, 29) to listOf("Jasnobrązowy", "Mocna pomarańcza"),
    intArrayOf(230, 103, 113) to listOf("Jasny Karminowy Róż", "Miękka czerwień"),
    intArrayOf(240, 128, 128) to listOf("Jasny Koral", "Miękka czerwień"),
    intArrayOf(147, 204, 234) to listOf("Jasno Chabrowy", "Bardzo miękki niebieski"),
    intArrayOf(224, 255, 255) to listOf("Jasny Cyjan", "Bardzo blady cyjan"),
    intArrayOf(249, 132, 239) to listOf("Jasny Róż W Kolorze Fuksji", "Miękka magenta"),
    intArrayOf(250, 250, 210) to listOf("Light Goldenrod Yellow", "Jasnoszary żółtawy"),
    intArrayOf(211, 211, 211) to listOf("Jasny Szary", "Jasny szary"),
    intArrayOf(144, 238, 144) to listOf("Jasnozielony", "Bardzo miękka limonkowa zieleń"),
    intArrayOf(240, 230, 140) to listOf("Jasny Khaki", "Bardzo delikatny żółty"),
    intArrayOf(177, 156, 217) to listOf("Jasny Pastelowy Fiolet", "Bardzo delikatny fiolet"),
    intArrayOf(255, 182, 193) to listOf("Jasnoróżowy", "Jasnoczerwony"),
    intArrayOf(255, 160, 122) to listOf("Jasny Łososiowy", "Bardzo jasny pomarańczowy"),
    intArrayOf(255, 153, 153) to listOf("Jasny Łososiowy Róż", "Bardzo jasna czerwień"),
    intArrayOf(32, 178, 170) to listOf("Jasna Morska Zieleń", "Ciemny cyjan"),
    intArrayOf(135, 206, 250) to listOf("Jasnoniebieski", "Miękki niebieski"),
    intArrayOf(119, 136, 153) to listOf("Light Slate Gray", "Ciemnoszary niebieski"),
    intArrayOf(179, 139, 109) to listOf("Jasnoszary", "Lekko przesycona pomarańcza"),
    intArrayOf(255, 255, 237) to listOf("Jasnożółty ", "Bardzo blady (przeważnie biały) żółty"),
    intArrayOf(200, 162, 200) to listOf("Bezowy", "Szarawy magenta"),
    intArrayOf(50, 205, 50) to listOf("Limonkowo Zielony ", "Mocna limonkowa zieleń"),
    intArrayOf(25, 89, 5) to listOf("Trawiasty Zielony ", "Bardzo ciemna limonkowa zieleń"),
    intArrayOf(250, 240, 230) to listOf("Lniany", "Jasno szaro-pomarańczowy"),
    intArrayOf(83, 75, 79) to listOf("Liver", "Bardzo ciemny szaro-różowy"),
    intArrayOf(230, 32, 32) to listOf("Lust", "Żywe czerwone"),
    intArrayOf(24, 69, 59) to listOf("Msu Green", "Bardzo ciemny cyjan"),
    intArrayOf(255, 189, 136) to listOf("Macaroni And Cheese", "Bardzo jasny pomarańczowy"),
    intArrayOf(170, 240, 209) to listOf("Magic Mint", "Bardzo delikatny cyjan - limonkowa zieleń"),
    intArrayOf(248, 244, 255) to listOf("Magnolia", "Bardzo blady (głównie biały) fiolet"),
    intArrayOf(192, 64, 0) to listOf("Mahoniowy", "Mocna pomarańcza"),
    intArrayOf(96, 80, 220) to listOf("Majorelle Blue", "Miękki niebieski"),
    intArrayOf(11, 218, 81) to listOf("Malachitowy", "Żywy cyjan - limonkowa zieleń"),
    intArrayOf(151, 154, 170) to listOf("Manatee", "Ciemnoszary niebieski"),
    intArrayOf(255, 130, 67) to listOf("Mango Tango", "Jasnopomarańczowy"),
    intArrayOf(116, 195, 101) to listOf("Modliszkowy", "Lekko desaturowana limonkowa zieleń"),
    intArrayOf(128, 0, 0) to listOf("Maroon", "Ciemno czerwony"),
    intArrayOf(224, 176, 255) to listOf("Fioletoworóżowy ", "Jasny fiolet"),
    intArrayOf(145, 95, 109) to listOf("Raspberry Glace", "Przeważnie desaturowany ciemny róż"),
    intArrayOf(239, 152, 170) to listOf("Mauvelous", "Bardzo miękka czerwień"),
    intArrayOf(115, 194, 251) to listOf("Maya Blue", "Miękki niebieski"),
    intArrayOf(229, 183, 59) to listOf("Mięsny Brąz", "Jasno pomarańczowy"),
    intArrayOf(0, 103, 165) to listOf("Średni Perski Niebieski", "Ciemny niebieski"),
    intArrayOf(102, 221, 170) to listOf("Średni Akwamaryn", "Delikatny cyjan - limonkowa zieleń"),
    intArrayOf(0, 0, 205) to listOf("Średni Niebieski", "Mocny niebieski"),
    intArrayOf(226, 6, 44) to listOf("Medium Candy Apple Red", "Żywe czerwone"),
    intArrayOf(175, 64, 53) to listOf("Blady Karmin", "Ciemna umiarkowana czerwień"),
    intArrayOf(243, 229, 171) to listOf("Waniliowy", "Bardzo delikatny żółty"),
    intArrayOf(3, 80, 150) to listOf("Średni Elektryczny Niebieski", "Ciemny niebieski"),
    intArrayOf(28, 53, 45) to listOf("Średnia Zieleń Dżungli", "Bardzo ciemny denasycony cyjan - limonkowa zieleń"),
    intArrayOf(221, 160, 221) to listOf("Śliwka", "Bardzo miękka magenta"),
    intArrayOf(186, 85, 211) to listOf("Średnia Orchidea", "Umiarkowana magenta"),
    intArrayOf(147, 112, 219) to listOf("Średni Fioletowy", "Miękki fiolet"),
    intArrayOf(187, 51, 133) to listOf("Średni Czerwony Fiolet", "Umiarkowany róż"),
    intArrayOf(60, 179, 113) to listOf("Średnia Morska Zieleń", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(123, 104, 238) to listOf("Średni Łupkowy Niebieski", "Miękki niebieski"),
    intArrayOf(201, 220, 135) to listOf("Średni Wiosenny Pąk", "Bardzo delikatny żółty"),
    intArrayOf(0, 250, 154) to listOf("Średnia Wiosenna Zieleń", "Czysty (lub w większości czysty) cyjan - limonkowa zieleń"),
    intArrayOf(103, 76, 71) to listOf("Średnioszary", "Bardzo ciemny szaro-czerwony"),
    intArrayOf(0, 84, 180) to listOf("Średni Turkusowo-Niebieski", "Mocny niebieski"),
    intArrayOf(72, 209, 204) to listOf("Średni Turkus", "Umiarkowany cyjan"),
    intArrayOf(199, 21, 133) to listOf("Czerwony Fiolet", "Mocny róż"),
    intArrayOf(253, 188, 180) to listOf("Melonowy", "Bardzo miękka czerwień"),
    intArrayOf(25, 25, 112) to listOf("Ciemny Granat", "Bardzo ciemnoniebieski"),
    intArrayOf(0, 73, 83) to listOf("Midnight Green", "Bardzo ciemny cyjan"),
    intArrayOf(255, 196, 12) to listOf("Żółty Mikado", "Żywy żółty"),
    intArrayOf(62, 180, 137) to listOf("Miętowy", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(245, 255, 250) to listOf("Krem Miętowy", "Bardzo blady (głównie biały) cyjan - limonkowy"),
    intArrayOf(152, 255, 152) to listOf("Jasnozielony", "Bardzo jasna limonkowa zieleń"),
    intArrayOf(255, 228, 225) to listOf("Mglista Róża", "Bardzo bladoczerwony (różowy odcień)"),
    intArrayOf(115, 169, 194) to listOf("Moonstone Blue", "Lekko przesycony niebieski"),
    intArrayOf(174, 12, 0) to listOf("Mordant Red 19", "Ciemno czerwony"),
    intArrayOf(173, 223, 173) to listOf("Nasycona Zieleń ", "Bardzo miękka limonkowa zieleń"),
    intArrayOf(48, 186, 143) to listOf("Górska Łąka", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(153, 122, 141) to listOf("Mountbatten Pink", "Ciemnoszary róż"),
    intArrayOf(197, 75, 140) to listOf("Morwa", "Umiarkowany róż"),
    intArrayOf(255, 219, 88) to listOf("Musztarda", "Jasny zółty"),
    intArrayOf(33, 66, 30) to listOf("Myrtle", "Bardzo ciemna desaturowana limonkowa zieleń"),
    intArrayOf(246, 173, 198) to listOf("Nadeshiko Pink", "Bardzo delikatny róż"),
    intArrayOf(42, 128, 0) to listOf("Napier Green", "Ciemnozielony"),
    intArrayOf(255, 222, 173) to listOf("Biały Navajo", "Jasnopomarańczowy"),
    intArrayOf(0, 0, 128) to listOf("Granatowy ", "Ciemny niebieski"),
    intArrayOf(255, 163, 67) to listOf("Neonowa Marchewka", "Jasnopomarańczowy"),
    intArrayOf(254, 89, 194) to listOf("Neonowa Fuksja", "Delikatny róż"),
    intArrayOf(57, 255, 20) to listOf("Neonowa Zieleń", "Żywa limonkowa zieleń"),
    intArrayOf(164, 221, 237) to listOf("Non-Photo Blue", "Bardzo delikatny cyjan"),
    intArrayOf(5, 144, 51) to listOf("North Texas Green", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(0, 119, 190) to listOf("Ocean Boat Blue", "Mocny niebieski"),
    intArrayOf(204, 119, 34) to listOf("Ochra", "Mocna pomarańcza"),
    intArrayOf(207, 181, 59) to listOf("Stare Złoto", "Umiarkowany żółty"),
    intArrayOf(253, 245, 230) to listOf("Old Lace", "Jasno szaro-pomarańczowy"),
    intArrayOf(121, 104, 120) to listOf("Brudny Lawendowy", "Ciemno szarawy magenta"),
    intArrayOf(103, 49, 71) to listOf("Old Mauve", "Bardzo ciemny, przygaszony róż"),
    intArrayOf(192, 128, 129) to listOf("Brudny Róż ", "Lekko przesycona czerwień"),
    intArrayOf(107, 142, 35) to listOf("Szarooliwkowy ", "Ciemnozielony"),
    intArrayOf(186, 184, 108) to listOf("Oliwkowa Zieleń ", "Lekko przesycona żółć"),
    intArrayOf(154, 185, 115) to listOf("Olivine", "Lekko przesycona zieleń"),
    intArrayOf(15, 15, 15) to listOf("Onyx", "Bardzo ciemnoszary (głównie czarny)"),
    intArrayOf(183, 132, 167) to listOf("Operowy Fiolet", "Lekko przygaszony róż"),
    intArrayOf(255, 165, 0) to listOf("Pomarańczowy", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(248, 213, 104) to listOf("Pomarańczowy Żółty", "Miękki żółty"),
    intArrayOf(255, 159, 0) to listOf("Skórka Pomarańczowa", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(255, 69, 0) to listOf("Pomarańczowy Czerwony", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(218, 112, 214) to listOf("Orchidea", "Miękka magenta"),
    intArrayOf(65, 74, 76) to listOf("Outer Space", "Bardzo ciemny szaro-błękitny"),
    intArrayOf(255, 110, 74) to listOf("Outrageous Orange", "Jasnoczerwony"),
    intArrayOf(0, 33, 71) to listOf("Błękit Oksfordzki ", "Bardzo ciemnoniebieski"),
    intArrayOf(28, 169, 201) to listOf("Pacyficzny Niebieski", "Mocny cyjan"),
    intArrayOf(0, 102, 0) to listOf("Pakistańska Zieleń", "Bardzo ciemna limonkowa zieleń"),
    intArrayOf(39, 59, 226) to listOf("Palatynat Niebieski", "Jasnoniebieski"),
    intArrayOf(104, 40, 96) to listOf("Palatynat Purpurowy", "Bardzo ciemny magenta"),
    intArrayOf(175, 238, 238) to listOf("Blady Niebieski", "Bardzo delikatny cyjan"),
    intArrayOf(152, 118, 84) to listOf("Bladobrązowy", "Przeważnie desaturowany ciemnopomarańczowy"),
    intArrayOf(155, 196, 226) to listOf("Blady Cerulean", "Bardzo miękki niebieski"),
    intArrayOf(221, 173, 175) to listOf("Jasny Kasztan", "Bardzo miękka czerwień"),
    intArrayOf(218, 138, 103) to listOf("Blada Miedź", "Miękki pomarańczowy"),
    intArrayOf(171, 205, 239) to listOf("Jasny Chabrowy Błękit", "Bardzo miękki niebieski"),
    intArrayOf(230, 190, 138) to listOf("Blady Złoty", "Bardzo miękka pomarańcza"),
    intArrayOf(238, 232, 170) to listOf("Pale Goldenrod", "Bardzo delikatny żółty"),
    intArrayOf(152, 251, 152) to listOf("Blado Zielony ", "Bardzo miękka limonkowa zieleń"),
    intArrayOf(220, 208, 255) to listOf("Blada Lawenda", "Bardzo blady fiolet"),
    intArrayOf(249, 132, 229) to listOf("Jasnopurpurowy", "Miękka magenta"),
    intArrayOf(250, 218, 221) to listOf("Blady Różowy", "Jasno szaro-czerwony"),
    intArrayOf(219, 112, 147) to listOf("Jasnofioletowa Czerwień", "Delikatny róż"),
    intArrayOf(150, 222, 209) to listOf("Pale Robin Egg Blue", "Bardzo delikatny cyjan"),
    intArrayOf(201, 192, 187) to listOf("Blady Srebrny", "Szaro-pomarańczowy"),
    intArrayOf(236, 235, 189) to listOf("Blady Wiosenny Pąk", "Jasnoszary żółtawy"),
    intArrayOf(188, 152, 126) to listOf("Jasnoszary", "Lekko przesycona pomarańcza"),
    intArrayOf(120, 24, 74) to listOf("Pansy Purple", "Ciemno różowy"),
    intArrayOf(255, 239, 213) to listOf("Papaya Whip", "Bardzo blady pomarańczowy"),
    intArrayOf(174, 198, 207) to listOf("Pastelowy Niebieski", "Szaroniebieski"),
    intArrayOf(131, 105, 83) to listOf("Pastelowy Brąz", "Przeważnie desaturowany ciemnopomarańczowy"),
    intArrayOf(207, 207, 196) to listOf("Pastelowy Szary", "Szaro-żółty"),
    intArrayOf(119, 221, 119) to listOf("Pastelowa Zieleń", "Delikatna limonkowa zieleń"),
    intArrayOf(244, 154, 194) to listOf("Pastelowa Magenta", "Bardzo delikatny róż"),
    intArrayOf(255, 179, 71) to listOf("Pastelowy Pomarańczowy", "Jasnopomarańczowy"),
    intArrayOf(255, 209, 220) to listOf("Pudrowy Róż", "Bardzo bladoczerwony"),
    intArrayOf(179, 158, 181) to listOf("Pastelowy Fiolet", "Szarawy magenta"),
    intArrayOf(255, 105, 97) to listOf("Pastelowa Czerwień", "Jasnoczerwony"),
    intArrayOf(203, 153, 201) to listOf("Pastelowy Fiolet", "Szarawy magenta"),
    intArrayOf(253, 253, 150) to listOf("Pastelowy Żółty", "Bardzo delikatny żółty"),
    intArrayOf(128, 0, 128) to listOf("Fioletowy", "Ciemna magenta"),
    intArrayOf(255, 229, 180) to listOf("Brzoskwiniowy", "Jasnopomarańczowy"),
    intArrayOf(255, 218, 185) to listOf("Peach Puff", "Jasnopomarańczowy"),
    intArrayOf(250, 223, 173) to listOf("Peach Yellow", "Bardzo miękka pomarańcza"),
    intArrayOf(209, 226, 49) to listOf("Gruszkowy", "Jasny żółty"),
    intArrayOf(234, 224, 200) to listOf("Perłowy", "Jasno szaro-pomarańczowy"),
    intArrayOf(136, 216, 192) to listOf("Wodny Perłowy", "Nieco przesycony cyjan - limonkowa zieleń"),
    intArrayOf(230, 226, 0) to listOf("Peridot", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(28, 57, 187) to listOf("Perski Niebieski", "Mocny niebieski"),
    intArrayOf(50, 18, 122) to listOf("Perski Indygo", "Ciemny fiolet"),
    intArrayOf(217, 144, 88) to listOf("Perska Pomarańcza", "Miękki pomarańczowy"),
    intArrayOf(247, 127, 190) to listOf("Perski Róż", "Delikatny róż"),
    intArrayOf(112, 28, 28) to listOf("Perska Śliwka", "Bardzo ciemnoczerwony"),
    intArrayOf(204, 51, 51) to listOf("Perska Czerwień", "Mocna czerwień"),
    intArrayOf(254, 40, 162) to listOf("Róża Perska", "Jasnoróżowy"),
    intArrayOf(223, 0, 255) to listOf("Psychedelic Purple", "Czysta (lub w większości czysta) magenta"),
    intArrayOf(0, 15, 137) to listOf("Błękit Ftalowy", "Ciemny niebieski"),
    intArrayOf(18, 53, 36) to listOf("Zieleń Ftalo", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(253, 221, 230) to listOf("Piggy Pink", "Jasnoszary róż"),
    intArrayOf(1, 121, 111) to listOf("Sosnowy Zielony", "Ciemny cyjan"),
    intArrayOf(255, 192, 203) to listOf("Różowy", "Bardzo bladoczerwony"),
    intArrayOf(252, 116, 253) to listOf("Różowy Flaming", "Miękka magenta"),
    intArrayOf(247, 143, 167) to listOf("Różowy Sorbet", "Bardzo miękka czerwień"),
    intArrayOf(231, 172, 207) to listOf("Różowa Perła", "Bardzo delikatny róż"),
    intArrayOf(147, 197, 114) to listOf("Pistacja", "Lekko przesycona zieleń"),
    intArrayOf(229, 228, 226) to listOf("Platyna", "Jasno szaro-pomarańczowy"),
    intArrayOf(255, 90, 54) to listOf("Portland Orange", "Jasnoczerwony"),
    intArrayOf(176, 224, 230) to listOf("Pudrowy Niebieski", "Bardzo delikatny cyjan"),
    intArrayOf(255, 143, 0) to listOf("Princeton Orange", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(0, 49, 83) to listOf("Prussian Blue", "Bardzo ciemnoniebieski"),
    intArrayOf(204, 136, 153) to listOf("Brązowofioletowy", "Lekko przesycona czerwień"),
    intArrayOf(255, 117, 24) to listOf("Dyniowy", "Żywy pomarańczowy"),
    intArrayOf(105, 53, 156) to listOf("Purple Heart", "Ciemny umiarkowany fiolet"),
    intArrayOf(157, 129, 186) to listOf("Purple Mountain'S Majesty", "Lekko przyciemniony fiolet"),
    intArrayOf(150, 120, 182) to listOf("Purple Mountain Majesty", "Lekko przyciemniony fiolet"),
    intArrayOf(254, 78, 218) to listOf("Purple Pizzazz", "Miękka magenta"),
    intArrayOf(80, 64, 77) to listOf("Fioletowy Ciemnoszary", "Bardzo ciemny szarawy magenta"),
    intArrayOf(255, 53, 94) to listOf("Radical Red", "Jasnoczerwony"),
    intArrayOf(227, 11, 93) to listOf("Malinowy", "Żywy róż"),
    intArrayOf(226, 80, 152) to listOf("Raspberry Pink", "Delikatny róż"),
    intArrayOf(179, 68, 108) to listOf("Malinowa Róża", "Umiarkowany róż"),
    intArrayOf(214, 138, 89) to listOf("Raw Sienna", "Umiarkowany pomarańczowy"),
    intArrayOf(255, 51, 204) to listOf("Razzle Dazzle Rose", "Żywy róż"),
    intArrayOf(227, 37, 107) to listOf("Razzmatazz", "Jasnoróżowy"),
    intArrayOf(255, 0, 0) to listOf("Czerwony", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(255, 83, 73) to listOf("Czerwony Pomarańczowy", "Jasnoczerwony"),
    intArrayOf(0, 64, 64) to listOf("Bogata Czerń", "Bardzo ciemny cyjan"),
    intArrayOf(215, 0, 64) to listOf("Bogaty Karmin", "Mocny róż"),
    intArrayOf(8, 146, 208) to listOf("Bogaty Elektryczny Błękit", "Mocny niebieski"),
    intArrayOf(182, 102, 210) to listOf("Bogaty Liliowy", "Umiarkowany fiolet"),
    intArrayOf(176, 48, 96) to listOf("Bogaty Bordowy", "Ciemno różowy"),
    intArrayOf(65, 72, 51) to listOf("Rifle Green", "Bardzo ciemny szaro zielony"),
    intArrayOf(31, 206, 203) to listOf("Robin'S Egg Blue", "Mocny cyjan"),
    intArrayOf(249, 66, 158) to listOf("Różany Cukierek", "Jasnoróżowy"),
    intArrayOf(103, 72, 70) to listOf("Heban Różany", "Bardzo ciemny szaro-czerwony"),
    intArrayOf(183, 110, 121) to listOf("Różowe Złoto", "Lekko przesycona czerwień"),
    intArrayOf(255, 102, 204) to listOf("Różowy Róż", "Jasnoróżowy"),
    intArrayOf(170, 152, 169) to listOf("Kwarc Różowy", "Ciemno szarawy magenta"),
    intArrayOf(144, 93, 93) to listOf("Różowoszary", "Przeważnie desaturowana ciemna czerwień"),
    intArrayOf(171, 78, 82) to listOf("Dolina Róż", "Ciemna umiarkowana czerwień"),
    intArrayOf(101, 0, 11) to listOf("Palisandrowy", "Bardzo ciemnoczerwony"),
    intArrayOf(212, 0, 0) to listOf("Corsa Rosso", "Mocna czerwień"),
    intArrayOf(188, 143, 143) to listOf("Różowo-Brązowy", "Szaro-czerwony"),
    intArrayOf(0, 56, 168) to listOf("Królewski Lazur", "Ciemny niebieski"),
    intArrayOf(65, 105, 225) to listOf("Królewski Niebieski", "Jasnoniebieski"),
    intArrayOf(202, 44, 146) to listOf("Królewska Fuksja", "Mocny róż"),
    intArrayOf(120, 81, 169) to listOf("Królewski Fiolet", "Ciemny umiarkowany fiolet"),
    intArrayOf(224, 17, 95) to listOf("Rubinowy", "Żywy róż"),
    intArrayOf(255, 0, 40) to listOf("Rumiany", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(187, 101, 40) to listOf("Rumiany Brąz", "Mocna pomarańcza"),
    intArrayOf(225, 142, 150) to listOf("Rumiany Róż", "Bardzo miękka czerwień"),
    intArrayOf(168, 28, 7) to listOf("Rufous", "Ciemno czerwony"),
    intArrayOf(128, 70, 27) to listOf("Rudy", "Ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(183, 65, 14) to listOf("Rdzawy", "Mocna pomarańcza"),
    intArrayOf(0, 86, 63) to listOf("Sacramento State Green", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(139, 69, 19) to listOf("Brązowe Siodło", "Ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(255, 103, 0) to listOf("Safety Orange", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(244, 196, 48) to listOf("Szafran", "Jasny żółty"),
    intArrayOf(35, 41, 122) to listOf("Saint Patrick Blue", "Ciemny niebieski"),
    intArrayOf(255, 140, 105) to listOf("Łososiowy", "Bardzo jasna czerwień"),
    intArrayOf(255, 145, 164) to listOf("Łososiowy Róż", "Bardzo jasna czerwień"),
    intArrayOf(236, 213, 64) to listOf("Burza Piaskowa", "Jasny żółty"),
    intArrayOf(244, 164, 96) to listOf("Piaskowy Brąz", "Miękki pomarańczowy"),
    intArrayOf(80, 125, 42) to listOf("Sap Green", "Ciemna umiarkowana zieleń"),
    intArrayOf(15, 82, 186) to listOf("Szafir", "Mocny niebieski"),
    intArrayOf(203, 161, 53) to listOf("Satin Sheen Gold", "Umiarkowany pomarańczowy"),
    intArrayOf(255, 36, 0) to listOf("Szkarłat", "Czysta (lub w większości czysta) czerwień"),
    intArrayOf(255, 216, 0) to listOf("School Bus Yellow", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(118, 255, 122) to listOf("Screamin Green", "Bardzo jasna limonkowa zieleń"),
    intArrayOf(0, 105, 148) to listOf("Morski Niebieski", "Ciemny niebieski"),
    intArrayOf(46, 139, 87) to listOf("Zielone Morze", "Ciemny umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(50, 20, 20) to listOf("Seal Brown", "Bardzo ciemna (głównie czarna) czerwień"),
    intArrayOf(255, 245, 238) to listOf("Seashell", "Bardzo blady (głównie biały) pomarańczowy"),
    intArrayOf(255, 186, 0) to listOf("Selective Yellow", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(112, 66, 20) to listOf("Sepia", "Bardzo ciemnopomarańczowy (odcień brązu)"),
    intArrayOf(138, 121, 93) to listOf("Shadow", "Przeważnie desaturowany ciemnopomarańczowy"),
    intArrayOf(69, 206, 162) to listOf("Shamrock", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(0, 158, 96) to listOf("Shamrock Green", "Ciemny cyjan - limonkowa zieleń"),
    intArrayOf(252, 15, 192) to listOf("Shocking Pink", "Żywy róż"),
    intArrayOf(136, 45, 23) to listOf("Sienna", "Ciemno czerwony"),
    intArrayOf(192, 192, 192) to listOf("Srebrny", "Jasny szary"),
    intArrayOf(203, 65, 11) to listOf("Sinopia", "Mocna pomarańcza"),
    intArrayOf(0, 116, 116) to listOf("Skobeloff", "Ciemny cyjan"),
    intArrayOf(135, 206, 235) to listOf("Niebieskie Niebo", "Bardzo miękki niebieski"),
    intArrayOf(207, 113, 175) to listOf("Niebo Magenta", "Lekko przygaszony róż"),
    intArrayOf(106, 90, 205) to listOf("Slate Blue", "Umiarkowany niebieski"),
    intArrayOf(112, 128, 144) to listOf("Popielaty", "Ciemnoszary niebieski"),
    intArrayOf(147, 61, 65) to listOf("Przydymiony Topaz", "Ciemna umiarkowana czerwień"),
    intArrayOf(16, 12, 8) to listOf("Przydymiona Czerń", "Bardzo ciemny (głównie czarny) pomarańczowy (odcień brązu)"),
    intArrayOf(255, 250, 250) to listOf("Śnieżny", "Bardzo blady (głównie biały) czerwony"),
    intArrayOf(15, 192, 252) to listOf("Spiro Disco Ball", "Żywy niebieski"),
    intArrayOf(167, 252, 0) to listOf("Spring Bud", "Czysta (lub w większości czysta) zieleń"),
    intArrayOf(70, 130, 180) to listOf("Stalowo - Niebieski", "Umiarkowany niebieski"),
    intArrayOf(0, 128, 128) to listOf("Teal", "Ciemny cyjan"),
    intArrayOf(228, 217, 111) to listOf("Straw", "Miękki żółty"),
    intArrayOf(255, 204, 51) to listOf("Słoneczny Blask", "Żywy żółty"),
    intArrayOf(253, 94, 83) to listOf("Pomarańczowy Zachód Słońca", "Miękka czerwień"),
    intArrayOf(210, 180, 140) to listOf("Tan", "Lekko przesycona pomarańcza"),
    intArrayOf(249, 77, 0) to listOf("Tangelo", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(242, 133, 0) to listOf("Mandarynkowy", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(255, 204, 0) to listOf("Złoto Usc", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(139, 133, 137) to listOf("Szary", "Ciemnoszary róż"),
    intArrayOf(205, 87, 0) to listOf("Płowy", "Mocna pomarańcza"),
    intArrayOf(208, 240, 192) to listOf("Zielony", "Bardzo miękka zieleń"),
    intArrayOf(54, 117, 136) to listOf("Zielononiebieski", "Ciemny umiarkowany cyjan"),
    intArrayOf(0, 109, 91) to listOf("Zielony", "Bardzo ciemny cyjan"),
    intArrayOf(226, 114, 91) to listOf("Terakota", "Miękka czerwień"),
    intArrayOf(216, 191, 216) to listOf("Thistle", "Szarawy magenta"),
    intArrayOf(222, 111, 161) to listOf("Thulian Pink", "Delikatny róż"),
    intArrayOf(252, 137, 172) to listOf("Tickle Me Pink", "Delikatny róż"),
    intArrayOf(10, 186, 181) to listOf("Tiffany Blue", "Mocny cyjan"),
    intArrayOf(224, 141, 60) to listOf("Tiger Eye", "Jasno pomarańczowy"),
    intArrayOf(219, 215, 210) to listOf("Timberwolf", "Jasno szaro-pomarańczowy"),
    intArrayOf(238, 230, 0) to listOf("Żółty Tytan", "Czysty (lub w większości czysty) żółty"),
    intArrayOf(255, 99, 71) to listOf("Pomidor", "Jasnoczerwony"),
    intArrayOf(116, 108, 192) to listOf("Toolbox", "Lekko przesycony niebieski"),
    intArrayOf(255, 200, 124) to listOf("Topaz", "Bardzo jasny pomarańczowy"),
    intArrayOf(253, 14, 53) to listOf("Tractor Red", "Żywe czerwone"),
    intArrayOf(0, 117, 94) to listOf("Tropikalne Lasy Deszczowe", "Ciemny cyjan"),
    intArrayOf(0, 115, 207) to listOf("Prawdziwy Niebieski", "Mocny niebieski"),
    intArrayOf(65, 125, 193) to listOf("Tufts Blue", "Umiarkowany niebieski"),
    intArrayOf(222, 170, 136) to listOf("Tumbleweed", "Bardzo miękka pomarańcza"),
    intArrayOf(181, 114, 129) to listOf("Róża Turecka", "Lekko przesycona czerwień"),
    intArrayOf(48, 213, 200) to listOf("Turkus", "Mocny cyjan"),
    intArrayOf(0, 255, 239) to listOf("Turkusowy Niebieski", "Czysty (lub w większości czysty) cyjan"),
    intArrayOf(160, 214, 180) to listOf("Turkusowy Zielony", "Nieco przesycony cyjan - limonkowa zieleń"),
    intArrayOf(102, 66, 77) to listOf("Toskańska Czerwień", "Bardzo ciemny, przygaszony róż"),
    intArrayOf(138, 73, 107) to listOf("Zmierzch Lawendy", "Ciemny umiarkowany róż"),
    intArrayOf(102, 2, 60) to listOf("Purpurowy", "Bardzo ciemny róż"),
    intArrayOf(0, 51, 170) to listOf("Niebieski Ua", "Ciemny niebieski"),
    intArrayOf(217, 0, 76) to listOf("Czerwony Ua", "Czysty (lub w większości czysty) róż"),
    intArrayOf(83, 104, 149) to listOf("Niebieski Ucla", "Przeważnie desaturowany ciemnoniebieski"),
    intArrayOf(255, 179, 0) to listOf("Złoto Ucla", "Czysta (lub w większości czysta) pomarańcza"),
    intArrayOf(60, 208, 112) to listOf("Zielony Ufo", "Umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(1, 68, 33) to listOf("Leśna Zieleń Up", "Bardzo ciemny cyjan - limonkowa zieleń"),
    intArrayOf(123, 17, 19) to listOf("Bordowy Up", "Ciemno czerwony"),
    intArrayOf(136, 120, 195) to listOf("Ube", "Lekko przesycony niebieski"),
    intArrayOf(255, 111, 255) to listOf("Ultra Pink", "Bardzo jasna magenta"),
    intArrayOf(18, 10, 143) to listOf("Ultramaryna", "Ciemny niebieski"),
    intArrayOf(65, 102, 245) to listOf("Ultramarynowy Błękit", "Jasnoniebieski"),
    intArrayOf(99, 81, 71) to listOf("Umber", "Bardzo ciemny szaro-pomarańczowy"),
    intArrayOf(91, 146, 229) to listOf("Niebieski Onz", "Miękki niebieski"),
    intArrayOf(183, 135, 39) to listOf("University Of California Gold", "Mocna pomarańcza"),
    intArrayOf(255, 255, 102) to listOf("Unmellow Yellow", "Jasny zółty"),
    intArrayOf(174, 32, 41) to listOf("Upsdell Red", "Ciemno czerwony"),
    intArrayOf(225, 173, 33) to listOf("Urobilin", "Żywy pomarańczowy"),
    intArrayOf(211, 0, 63) to listOf("Szkarłat Utah", "Mocny róż"),
    intArrayOf(197, 179, 88) to listOf("Vegas Gold", "Umiarkowany żółty"),
    intArrayOf(200, 8, 21) to listOf("Wenecka Czerwień", "Mocna czerwień"),
    intArrayOf(67, 179, 174) to listOf("Verdigris", "Umiarkowany cyjan"),
    intArrayOf(160, 32, 240) to listOf("Veronica", "Żywy fiolet"),
    intArrayOf(50, 74, 178) to listOf("Liliowoniebieski", "Ciemny niebieski"),
    intArrayOf(247, 83, 148) to listOf("Violet Red", "Delikatny róż"),
    intArrayOf(64, 130, 109) to listOf("Viridian", "Ciemny umiarkowany cyjan - limonkowa zieleń"),
    intArrayOf(146, 39, 36) to listOf("Żywy Kasztan", "Ciemno czerwony"),
    intArrayOf(159, 29, 53) to listOf("Żywy Burgund", "Ciemno czerwony"),
    intArrayOf(218, 29, 129) to listOf("Żywy Wiśniowy", "Żywy róż"),
    intArrayOf(255, 160, 137) to listOf("Żywa Mandarynka", "Bardzo jasna czerwień"),
    intArrayOf(159, 0, 255) to listOf("Żywy Fiolet", "Czysty (lub w większości czysty) fiolet"),
    intArrayOf(0, 66, 66) to listOf("Ciepła Czerń", "Bardzo ciemny cyjan"),
    intArrayOf(100, 84, 82) to listOf("Wenge", "Bardzo ciemny szaro-czerwony"),
    intArrayOf(245, 222, 179) to listOf("Wheat", "Bardzo miękka pomarańcza"),
    intArrayOf(255, 255, 255) to listOf("Biały", "Biały"),
    intArrayOf(245, 245, 245) to listOf("Biały Dym", "Bardzo jasnoszary (głównie biały)"),
    intArrayOf(255, 67, 164) to listOf("Dzika Truskawka", "Jasnoróżowy"),
    intArrayOf(252, 108, 133) to listOf("Dziki Arbuz", "Miękka czerwień"),
    intArrayOf(162, 173, 208) to listOf("Wild Blue Yonder", "Szaroniebieski"),
    intArrayOf(114, 47, 55) to listOf("Wino", "Bardzo ciemna desaturowana czerwień"),
    intArrayOf(201, 160, 220) to listOf("Wisteria", "Bardzo delikatny fiolet"),
    intArrayOf(115, 134, 120) to listOf("Xanadu", "Ciemnoszary cyjan - limonkowa zieleń"),
    intArrayOf(15, 77, 146) to listOf("Yale Blue", "Ciemny niebieski"),
    intArrayOf(255, 174, 66) to listOf("Żółty Pomarańczowy", "Jasnopomarańczowy"),
    intArrayOf(154, 205, 50) to listOf("Żółty Zielony", "Mocna zieleń"),
    intArrayOf(0, 20, 168) to listOf("Zaffre", "Ciemny niebieski"),
    intArrayOf(44, 22, 8) to listOf("Zinnwaldite Brown", "Bardzo ciemny (głównie czarny) pomarańczowy (odcień brązu)")
)