package com.daltowacja.daltowacja

val basicColors_en = mapOf(
    intArrayOf(255, 0, 0) to listOf("Red", "Intense color like red traffic lights"),
    intArrayOf(200, 0, 0) to listOf("Red", "Intense color like red traffic lights"),
    intArrayOf(255, 100, 100) to listOf("Light Red", "Pale shade of red"),
    intArrayOf(255, 50, 50) to listOf("Light Red", "Pale shade of red"),
    intArrayOf(200, 50, 50) to listOf("Light Red", "Pale shade of red"),
    intArrayOf(150, 50, 50) to listOf("Light Red", "Pale shade of red"),
    intArrayOf(128, 0, 0) to listOf("Dark Red", "Deep, dark shade of red"),
    intArrayOf(128, 20, 20) to listOf("Dark Red", "Deep, dark shade of red"),
    intArrayOf(64, 0, 0) to listOf("Very Dark Red", "Deep and intense shade of red, almost black"),
    intArrayOf(64, 20, 20) to listOf("Very Dark Red", "Deep and intense shade of red, almost black"),

    intArrayOf(0, 255, 0) to listOf("Green", "Color of grass and leaves"),
    intArrayOf(0, 200, 0) to listOf("Green", "Color of grass and leaves"),
    intArrayOf(144, 238, 144) to listOf("Light Green", "Pale shade of green"),
    intArrayOf(128, 128, 50) to listOf("Light Green", "Pale shade of green"),
    intArrayOf(0, 128, 0) to listOf("Dark Green", "Deep, dark shade of green"),
    intArrayOf(20, 128, 20) to listOf("Dark Green", "Deep, dark shade of green"),
    intArrayOf(0, 64, 0) to listOf("Very Dark Green", "Deep and intense shade of green, almost black"),
    intArrayOf(20, 64, 20) to listOf("Very Dark Green", "Deep and intense shade of green, almost black"),
    intArrayOf(128, 255, 0) to listOf("Lime", "Intense shade of green, like a lime"),
    intArrayOf(100, 200, 0) to listOf("Lime", "Intense shade of green, like a lime"),

    intArrayOf(0, 0, 255) to listOf("Blue (dark)", "Color resembling the sky on a clear day"),
    intArrayOf(0, 0, 200) to listOf("Blue (dark)", "Color resembling the sky on a clear day"),
    intArrayOf(0, 128, 255) to listOf("Light Blue", "Pale shade of blue resembling the sky"),
    intArrayOf(0, 128, 200) to listOf("Light Blue", "Pale shade of blue resembling the sky"),
    intArrayOf(70, 70, 128) to listOf("Grayish-blue", "Shade of blue with a touch of gray"),
    intArrayOf(0, 255, 255) to listOf("Cyan", "Intense blue-green color"),
    intArrayOf(50, 255, 255) to listOf("Cyan", "Intense blue-green color"),
    intArrayOf(0, 255, 128) to listOf("Teal", "Color close to a turquoise shade, like sea water"),
    intArrayOf(50, 255, 128) to listOf("Teal", "Color close to a turquoise shade, like sea water"),

    intArrayOf(255, 100, 0) to listOf("Orange", "Color between red and yellow"),
    intArrayOf(255, 100, 50) to listOf("Orange", "Color between red and yellow"),
    intArrayOf(255, 75, 0) to listOf("Orange", "Color between red and yellow"),
    intArrayOf(255, 120, 0) to listOf("Light Orange", "Pale shade of orange"),
    intArrayOf(200, 100, 50) to listOf("Light Orange", "Pale shade of orange"),
    intArrayOf(255, 50, 0) to listOf("Dark Orange", "Deep, dark shade of orange"),
    intArrayOf(200, 50, 0) to listOf("Dark Orange", "Deep, dark shade of orange"),

    intArrayOf(255, 255, 0) to listOf("Yellow", "Bright color with a hue similar to sunlight"),
    intArrayOf(200, 200, 0) to listOf("Yellow", "Bright color with a hue similar to sunlight"),
    intArrayOf(255, 255, 128) to listOf("Light Yellow", "Pale shade of yellow"),
    intArrayOf(255, 255, 64) to listOf("Light Yellow", "Pale shade of yellow"),
    intArrayOf(200, 200, 128) to listOf("Light Yellow", "Pale shade of yellow"),
    intArrayOf(200, 140, 0) to listOf("Dark Yellow", "Deep, dark shade of yellow"),
    intArrayOf(180, 128, 20) to listOf("Dark Yellow", "Deep, dark shade of yellow"),

    intArrayOf(128, 0, 255) to listOf("Purple", "Color between blue and red"),
    intArrayOf(100, 0, 200) to listOf("Purple", "Color between blue and red"),
    intArrayOf(200, 100, 255) to listOf("Light Purple", "Pale shade of purple"),
    intArrayOf(128, 64, 160) to listOf("Light Purple", "Pale shade of purple"),

    intArrayOf(255, 0, 255) to listOf("Pink", "Intense color with shades of red and blue"),
    intArrayOf(255, 0, 200) to listOf("Pink", "Intense color with shades of red and blue"),
    intArrayOf(200, 0, 200) to listOf("Pink", "Intense color with shades of red and blue"),
    intArrayOf(255, 0, 128) to listOf("Fuchsia", "Pale shade of pink, like fuchsia flowers"),
    intArrayOf(200, 0, 100) to listOf("Fuchsia", "Pale shade of pink, like fuchsia flowers"),

    intArrayOf(0, 0, 0) to listOf("Black", "Lack of color or light reflection, darkest shade"),
    intArrayOf(20, 20, 20) to listOf("Black", "Lack of color or light reflection, darkest shade"),
    intArrayOf(128, 64, 0) to listOf("Brown", "Natural color resembling wood tone"),
    intArrayOf(100, 50, 0) to listOf("Brown", "Natural color resembling wood tone"),
    intArrayOf(200, 128, 50) to listOf("Light Brown", "Pale shade of brown"),
    intArrayOf(150, 100, 50) to listOf("Light Brown", "Pale shade of brown"),
    intArrayOf(100, 50, 0) to listOf("Dark Brown", "Deep, dark shade of brown"),
    intArrayOf(80, 40, 10) to listOf("Dark Brown", "Deep, dark shade of brown"),

    intArrayOf(255, 255, 255) to listOf("White", "Color reflecting all light wavelengths"),
    intArrayOf(200, 200, 200) to listOf("White", "Color reflecting all light wavelengths"),
    intArrayOf(100, 100, 100) to listOf("Gray", "Color between white and black"),
    intArrayOf(125, 125, 125) to listOf("Gray", "Color between white and black"),
    intArrayOf(150, 150, 150) to listOf("Gray", "Color between white and black"),
)
