package com.daltowacja.daltowacja

val basicColors_pl = mapOf(
    intArrayOf(255, 0, 0) to listOf("Czerwony", "Intensywny kolor jak czerwone światło sygnalizacji drogowej"),
    intArrayOf(200, 0, 0) to listOf("Czerwony", "Intensywny kolor jak czerwone światło sygnalizacji drogowej"),
    intArrayOf(255, 100, 100) to listOf("Jasnoczerwony", "Blada odcień czerwieni"),
    intArrayOf(255, 50, 50) to listOf("Jasnoczerwony", "Blada odcień czerwieni"),
    intArrayOf(200, 50, 50) to listOf("Jasnoczerwony", "Blada odcień czerwieni"),
    intArrayOf(150, 50, 50) to listOf("Jasnoczerwony", "Blada odcień czerwieni"),
    intArrayOf(128, 0, 0) to listOf("Ciemnoczerwony", "Głęboki, ciemny odcień czerwieni"),
    intArrayOf(128, 20, 20) to listOf("Ciemnoczerwony", "Głęboki, ciemny odcień czerwieni"),
    intArrayOf(64, 0, 0) to listOf("Bardzo Ciemny Czerwony", "Głęboki i intensywny odcień czerwieni, prawie czarny"),
    intArrayOf(64, 20, 20) to listOf("Bardzo Ciemny Czerwony", "Głęboki i intensywny odcień czerwieni, prawie czarny"),

    intArrayOf(0, 255, 0) to listOf("Zielony", "Kolor trawy i liści"),
    intArrayOf(0, 200, 0) to listOf("Zielony", "Kolor trawy i liści"),
    intArrayOf(144, 238, 144) to listOf("Jasnozielony", "Blady odcień zieleni"),
    intArrayOf(128, 128, 50) to listOf("Jasnozielony", "Blady odcień zieleni"),
    intArrayOf(0, 128, 0) to listOf("Ciemnozielony", "Głęboki, ciemny odcień zieleni"),
    intArrayOf(20, 128, 20) to listOf("Ciemnozielony", "Głęboki, ciemny odcień zieleni"),
    intArrayOf(0, 64, 0) to listOf("Bardzo Ciemny Zielony", "Głęboki i intensywny odcień zieleni, prawie czarny"),
    intArrayOf(20, 64, 20) to listOf("Bardzo Ciemny Zielony", "Głęboki i intensywny odcień zieleni, prawie czarny"),
    intArrayOf(128, 255, 0) to listOf("Limonkowy", "Intensywny odcień zieleni, jak limonka"),
    intArrayOf(100, 200, 0) to listOf("Limonkowy", "Intensywny odcień zieleni, jak limonka"),

    intArrayOf(0, 0, 255) to listOf("Niebieski (ciemny)", "Kolor przypominający niebo w bezchmurny dzień"),
    intArrayOf(0, 0, 200) to listOf("Niebieski (ciemny)", "Kolor przypominający niebo w bezchmurny dzień"),
    intArrayOf(0, 128, 255) to listOf("Jasnoniebieski", "Blady odcień niebieskiego przypominający niebo"),
    intArrayOf(0, 128, 200) to listOf("Jasnoniebieski", "Blady odcień niebieskiego przypominający niebo"),
    intArrayOf(70, 70, 128) to listOf("Szaroniebieski", "Odcień niebieskiego z domieszką szarości"),
    intArrayOf(0, 255, 255) to listOf("Błękitny", "Intensywny kolor niebiesko-zielony"),
    intArrayOf(50, 255, 255) to listOf("Błękitny", "Intensywny kolor niebiesko-zielony"),
    intArrayOf(0, 255, 128) to listOf("Turkusowy", "Kolor zbliżony do odcienia turkusu, jak woda morska"),
    intArrayOf(50, 255, 128) to listOf("Turkusowy", "Kolor zbliżony do odcienia turkusu, jak woda morska"),

    intArrayOf(255, 100, 0) to listOf("Pomarańczowy", "Kolor między czerwonym a żółtym"),
    intArrayOf(255, 100, 50) to listOf("Pomarańczowy", "Kolor między czerwonym a żółtym"),
    intArrayOf(255, 75, 0) to listOf("Pomarańczowy", "Kolor między czerwonym a żółtym"),
    intArrayOf(255, 120, 0) to listOf("Jasnopomarańczowy", "Blady odcień pomarańczy"),
    intArrayOf(200, 100, 50) to listOf("Jasnopomarańczowy", "Kolor między czerwonym a żółtym"),
    intArrayOf(255, 50, 0) to listOf("Ciemnopomarańczowy", "Głęboki, ciemny odcień pomarańczy"),
    intArrayOf(200, 50, 0) to listOf("Ciemnopomarańczowy", "Głęboki, ciemny odcień pomarańczy"),

    intArrayOf(255, 255, 0) to listOf("Żółty", "Jasny kolor o odcieniu podobnym do światła słonecznego"),
    intArrayOf(200, 200, 0) to listOf("Żółty", "Jasny kolor o odcieniu podobnym do światła słonecznego"),
    intArrayOf(255, 255, 128) to listOf("Jasnożółty", "Blady odcień żółtego"),
    intArrayOf(255, 255, 64) to listOf("Jasnożółty", "Blady odcień żółtego"),
    intArrayOf(200, 200, 128) to listOf("Jasnożółty", "Blady odcień żółtego"),
    intArrayOf(200, 140, 0) to listOf("Ciemnożółty", "Głęboki, ciemny odcień żółtego"),
    intArrayOf(180, 128, 20) to listOf("Ciemnożółty", "Głęboki, ciemny odcień żółtego"),

    intArrayOf(128, 0, 255) to listOf("Fioletowy", "Kolor między niebieskim a czerwonym"),
    intArrayOf(100, 0, 200) to listOf("Fioletowy", "Kolor między niebieskim a czerwonym"),
    intArrayOf(200, 100, 255) to listOf("Jasnofioletowy", "Blady odcień fioletowego"),
    intArrayOf(128, 64, 160) to listOf("Jasnofioletowy", "Blady odcień fioletowego"),

    intArrayOf(255, 0, 255) to listOf("Różowy", "Intensywny kolor o odcieniach czerwieni i niebieskiego"),
    intArrayOf(255, 0, 200) to listOf("Różowy", "Intensywny kolor o odcieniach czerwieni i niebieskiego"),
    intArrayOf(200, 0, 200) to listOf("Różowy", "Intensywny kolor o odcieniach czerwieni i niebieskiego"),
    intArrayOf(255, 0, 128) to listOf("Fuksja", "Blady odcień różowego, jak kwiaty fuksji"),
    intArrayOf(200, 0, 100) to listOf("Fuksja", "Blady odcień różowego, jak kwiaty fuksji"),

    intArrayOf(0, 0, 0) to listOf("Czarny", "Brak koloru lub odbicia światła, najciemniejszy odcień"),
    intArrayOf(20, 20, 20) to listOf("Czarny", "Brak koloru lub odbicia światła, najciemniejszy odcień"),
    intArrayOf(128, 64, 0) to listOf("Brązowy", "Naturalny kolor przypominający odcień drewna"),
    intArrayOf(100, 50, 0) to listOf("Brązowy", "Naturalny kolor przypominający odcień drewna"),
    intArrayOf(200, 128, 50) to listOf("Jasnobrązowy", "Blady odcień brązu"),
    intArrayOf(150, 100, 50) to listOf("Jasnobrązowy", "Blady odcień brązu"),
    intArrayOf(100, 50, 0) to listOf("Ciemnobrązowy", "Głęboki, ciemny odcień brązu"),
    intArrayOf(80, 40, 10) to listOf("Ciemnobrązowy", "Głęboki, ciemny odcień brązu"),

    intArrayOf(255, 255, 255) to listOf("Biały", "Kolor odbijający wszystkie długości fali świetlnej"),
    intArrayOf(200, 200, 200) to listOf("Biały", "Kolor odbijający wszystkie długości fali świetlnej"),
    intArrayOf(100, 100, 100) to listOf("Szary", "Kolor między białym a czarnym"),
    intArrayOf(125, 125, 125) to listOf("Szary", "Kolor między białym a czarnym"),
    intArrayOf(150, 150, 150) to listOf("Szary", "Kolor między białym a czarnym"),
)
